### ISSUE TITLE
Amp\lift

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#101]
Might fit into #100, but not sure on that.

**Comment by aenglander** [comment]
I can take this one and work on it this week.

**Comment by kelunik** [comment]
Awesome!

**Comment by kelunik** [comment]
@aenglander We just decided to drop `Amp\lift`, as there's not much use for it in a world with coroutines. And the name was bad anyway.

**Comment by aenglander** [comment]
No worries, I'll just pick off something else from the list.
