### ISSUE TITLE
Stream\interval naming

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#107]
I think we should remove the default value for `$count` and rename the function. Maybe `fromInterval`?

**Comment by bwoebi** [comment]
`$count` only matters if you use when(), but not if you just listen().
So, I see no point in removing that.

As for the naming, I see no clear benefit of fromInterval…

**Comment by kelunik** [comment]
Count matters either way, as it restricts the number of items.

**Comment by bwoebi** [comment]
Not if you want no restriction … default count will just be defacto no restriction (2^63 … seriously?)

**Comment by kelunik** [comment]
I don't see a reason to use it without restriction.

**Comment by kelunik** [comment]
This has been resolved by purging `interval` and adding `$delay` to `fromInterval`.
