### ISSUE TITLE
100% CPU usage with UV

### ISSUE THREAD

**Issue by umbri** [amphp/amp#112]
use https://github.com/umbri/Empower to reproduce the bug

1. start examples/ampv1/server1.php 
2. start examples/ampv1/client1.php
3. 100% CPU

only with ```UvDriver```, using ```EvDriver``` all is OK

**Comment by kelunik** [comment]
With `NativeDriver` it's also fine.

**Comment by kelunik** [comment]
I could reproduce it and have PHP 7.1.3RC1 with the following `uv` versions running.

```
uv
PHP libuv Extension

libuv Support => enabled
Version => 0.1.2
libuv Version => 1.11
```

**Comment by kelunik** [comment]
I'm going to close this one, as no one of us is going to invest work into this. Please upgrade to Amp v2.
