### ISSUE TITLE
Timers not enabled immediately

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#113]
https://github.com/amphp/amp/blob/2f7e9a0746e718ee2d64ab51c5aad8f5748eaa74/lib/Loop/Driver.php#L190-L191 states:

> The created watcher MUST immediately be marked as enabled, but only be activated (i.e. callback can be called) right before the next tick. Callbacks of watchers MUST NOT be called in the tick they were enabled.

Currently our timer watchers are created in `activate` and thus are only enabled right before the next tick instead of immediately. It doesn't really matter for running loops, but it's a compatibility issue with ReactPHP, as their tests create a timer, `usleep` for it's duration, and do a tick afterwards.

This _might_ be an issue in combination with `Amp\wait`.

**Comment by bwoebi** [comment]
Yeah, the time relative to the point of creation should count, not the time relative to the point of actual activation. This would otherwise probably lead to weird behavior if you disable and reenable timer watchers?

**Comment by kelunik** [comment]
Reenabled timers always count from the time of enabling, not the original time.

**Comment by bwoebi** [comment]
Question: What exactly are our options how to fix this?

**Comment by kelunik** [comment]
We could check for `!$this->running` and activate watchers immediately in that case.

**Comment by trowski** [comment]
Should disabled timers count the time during which they were disabled?

We could fix this by adding another field to timer watchers that records the time when the watcher was either created or last executed, calculating the expiration time based on that time instead of the current time.

**Comment by kelunik** [comment]
I guess it's fine if disabled timer watchers are just not called if disabled, but keep counting.

**Comment by trowski** [comment]
I'm not sure I want to change our behavior just to satisfy React. libevent, libev, and libuv are closer to our current watcher behavior.

**Comment by bwoebi** [comment]
I can't decide what's sane for disabled timers…

Anyway, I'm in favor to have the time counting from the point of enabling. And not activation, which is more like an internal detail so that fresh watcher _handlers_ are only triggered within the next tick.
It won't make much difference (the only guarantee ultimately is the _least_ for timers), but will solve the React issue.

**Comment by kelunik** [comment]
Fixed via https://github.com/amphp/amp/commit/4792bf52fe5c7ac168eb845ad4437632964c3ba8.
