### ISSUE TITLE
Proposal: Clean, Merge, Standardize https://github.com/amphp

### ISSUE THREAD

**Issue by umbri** [amphp/amp#114]
1. Thank you all for this amazing product
2. Working with Amp (v1) I encounter some shortcomings (personal for me) may be someone else encounter same.
2.1. Amp has ```amphp/socket``` but ```(amphp/aerys``` && ```amphp/artax)``` don't use it (or partial use, with some black magic hacks)
2.2. ```amphp/artax``` has https://github.com/amphp/artax/blob/master/lib/Uri.php and there is also ```amphp/uri``` 
2.3. [Stream](https://github.com/amphp/amp/blob/master/lib/Stream.php) Interface is defined in ```amphp/amp``` but we have ```amphp/stream```
2.4. ```amphp/websocket``` same black magic as ```2.1```
2.5. To be continued ...
4. As I understand ```amphp/socket``` must be base component where other components that work with network sockets use it, and if we find any bugs in ```amphp/socket``` patch all at once, but most of components use network sockets internally with some black magic, and with personal implementation (optimizations), I don't think that performance from such black magic worth it, personally for me, as Amp user, just make things more complicated.

**Comment by kelunik** [comment]
What are the black magic hacks you're talking of? `aerys` doesn't use `socket` for performance reasons, `artax` doesn't use `socket` mainly because it's older than the `socket` additions like `Client`.

The `uri` package you're talking about is completely extracted from Artax, but that process isn't finalized yet. We have to fix a few things in `uri` and then `artax` v3 will use it.

`stream` is the actual stream abstraction, we should maybe find a better name for `Amp\Stream`.

Why *must* `socket` be the base component?

**Comment by umbri** [comment]
@kelunik  I really appreciate all you are doing, I just comment my personal problems I encounter when using Amp, I think you must Standardize or do something like this

**Comment by umbri** [comment]
@kelunik "Why must socket be the base component?", I only refer to network sockets, if component use them. 

P.S: Sorry for my English, there may be some misunderstandings

**Comment by bwoebi** [comment]
In general, I avoid using the amp/socket Server component in libraries. The Server class of amp/socket is not designed for complete control over watcher and socket, which you may need for rate-limiting etc. It is fine for low-traffic private endpoints, but not for servers open to wide public needing to potentially withstand larger amounts of traffic.

The client however is totally fine for use in our libraries, and will be used in future I guess.

**Comment by umbri** [comment]
@bwoebi May be we need a new component that will permit "complete control over watcher and socket, which you may need for rate-limiting etc."

After some code review I find that ```amphp/websocket``` && ```amphp/aerys``` and may be other components, are using ~ same network sockets, but with different implementations, and for my projects I need just a network socket server that will do ~ the same, and I need to rewrite same code. I think this is unproductive, there are plenty of stones in PHP sockets/streams + OS stones and limits (like: file descriptors, nf_conntrack_max, etc. ..) but this is out of scope here. 

My opinion is to write a network socket server that will solve all needs from ```amphp/websocket``` && ```amphp/aerys```, this will be extremely useful and productive

**Comment by bwoebi** [comment]
We do not need that component, that component is basically provided by amp itself. We do not win anything by putting more layers around it. We basically need all functionality Amp provides and cannot abstract anything away there. You do not end up saving any real code here.

AFAIK @trowski wanted to write something which couples socket management and parsing in one thing, at which point we would perhaps see some real thing abstracted away, where it becomes helpful.

**Comment by umbri** [comment]
@bwoebi Ups, I mean amphp/aerys, Thank you

**Comment by trowski** [comment]
@bwoebi @umbri I recently pushed what I was working on with the socket parser [here](https://github.com/amphp/socket/blob/parser/lib/Parser.php) in the `parser` branch of `amphp/socket`.

The namespace of `amphp/stream` is `Amp\ByteStream`. Perhaps the package should be named as such, `amphp/byte-stream`, or we should consider a different name for `Amp\Stream`.

@umbri You can use `Amp\Socket\Server` in the `amphp/socket` package to create a simple socket server. I think this will do most of what you want to do. Aerys doesn't really use any "black magic," it just doesn't use that class. If you look at the v2 implementation of `Amp\Socket\Server`, you'll see that it's actually rather trivial. Reproducing that logic where finer-grained control is needed is not a big deal.

One API I don't care for is `Amp\Message`. I think any usages of this class should be an instance of `Amp\ByteStream\ReadableStream`. We could then write any other API's around the stream interfaces, making interoperability between packages easier.

**Comment by umbri** [comment]
@trowski @bwoebi @kelunik I think we can close this.
Thank you all.
