### ISSUE TITLE
Loop example is broken

### ISSUE THREAD

**Issue by markkimsal** [amphp/amp#122]
amp/examples/basic/timers.php seems to have multiple issues.

Amp\Loop is in amphp/loop package, but there is no released version, so requiring in composer is tricky.

use Amp\Loop does not resolve to a class.
PHP Fatal error:  Uncaught Error: Class 'Amp\Loop' not found in examples/timers.php:6

Changing it to Loop\Loop::run() results in static access of $this
amphp/loop uses non-static loop objects created from a LoopFactory, but the example uses static functions Amp\Loop\Loop::run()

PHP Fatal error:  Uncaught Error: Using $this when not in object context in vendor/amphp/loop/lib/Loop.php:39

If I change it to $loop = \Amp\Loop\LoopFactory::create()
$loop->run( ... rest of example
);

None of the inside messages get printed.
Is there another loop interface other than amphp/loop ?

```
#!/usr/bin/env php
<?php
include_once('vendor/autoload.php');
use Amp\Loop;
print "-- before Loop::run()" . PHP_EOL;
$loop = \Amp\Loop\LoopFactory::create();
$loop->repeat(1000, function () { 
    print "++ Executing watcher created by Loop::repeat()" . PHP_EOL;
});

$loop->delay(5000, function () use($loop){
    print "++ Executing watcher created by Loop::delay()" . PHP_EOL;
    $loop->stop();
    print "++ Loop will continue the current tick and stop afterwards" . PHP_EOL;
});

$loop->run();
print "-- after Loop::run()" . PHP_EOL;
```

The above example works, but it is significantly different.  The existing loop project doesn't seem to use a similar static facade pattern that amphp uses.

**Comment by trowski** [comment]
`master` is for v2.0, which has not yet been tagged. You must specify `dev-master` as the version for `amphp/amp` (and `dev-amp_v2` for most other packages except `stream`, `parallel`, and `postgres`, which new to v2.0, so therefore also `dev-master`). `amphp/loop` has been merged into this repo, so there's no need to install it. We should probably just remove it.

Amp v2 will be tagged within the next few days and hopefully the installation pain with composer will quickly go away.

An example `require` section of `composer.json` to get you started:

```json
    "require": {
        "amphp/amp": "dev-master as 2.0",
        "amphp/parallel": "dev-master",
        "amphp/stream": "dev-master",
        "amphp/socket": "dev-amp_v2",
        "amphp/file": "dev-amp_v2"
    }
```

**Comment by kelunik** [comment]
As `amphp/loop` doesn't have any release, we should probably just completely purge it.

**Comment by kelunik** [comment]
```
$ php examples/basic/timers.php 
-- before Loop::run()
++ Executing watcher created by Loop::repeat()
++ Executing watcher created by Loop::repeat()
++ Executing watcher created by Loop::repeat()
++ Executing watcher created by Loop::repeat()
++ Executing watcher created by Loop::delay()
++ Loop will continue the current tick and stop afterwards
-- after Loop::run()
```

^ Works fine for me. Did you execute the examples when Amp is installed as dependency?

**Comment by kelunik** [comment]
Closing, as there has been no further feedback.

The `examples` directory isn't present in release archives and thus doesn't have to support the Composer autoloader when installed as a package instead of being the root package.
