### ISSUE TITLE
Inconsistent repeat watchers with interval = 0

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#131]
```php
$detector = new BlockDetector(..., $threshold, $interval);
$detector->start();

Loop::run(function () use ($detector) {
    Loop::repeat(0, function () {
        usleep(100 * 1000);
    });

    Loop::delay(300, function () {
        Loop::stop();
   });
});
```

Currently I have a bug that doesn't call the detector (migrated from the interop loop, worked before) with UV. With the `NativeDriver` it completely blocks and never stops.

**Comment by kelunik** [comment]
Works only fine in `EventDriver`, all others fail.

**Comment by kelunik** [comment]
I think we should move away from `SplPriorityQueue`, because we need a queue that inserts new items always after items with the same priority.

**Comment by bwoebi** [comment]
The issue in UV is that the underlying primitive (also on the C API level) interprets an interval of 0 as a single-time timer. (aka a delay watcher)
There is no such thing like a timer watcher triggering each time with uv.

Not sure what to do about this. But there's at least nothing I can do on the ext/uv side; we need a solution within this library.

**Comment by trowski** [comment]
Is there a reason to even allow interval = 0? That's what defer watchers are for… so while it is sort of just avoiding the problem, maybe it's a fine solution?

That being said I'm also find with moving away from `SplPriorityQueue`. Some time ago I wrote a version of `NativeDriver` using an array-based priority queue, I can dig that up again if we're interested.

**Comment by kelunik** [comment]
@trowski I use them to basically execute a timer in every tick. Yes, usually you don't want to do that.

See https://github.com/kelunik/loop-block/blob/master/src/BlockDetector.php.

**Comment by kelunik** [comment]
Fixed it for `NativeDriver`. `Uv` and `Ev` hang and thus fail this test: https://gist.github.com/kelunik/fc491501ef9d01e1cab3becb1ce6984c

**Comment by staabm** [comment]
Would it make sense to use a php-ds datastructure?

https://medium.com/@rtheunissen/efficient-data-structures-for-php-7-9dda7af674cd
