### ISSUE TITLE
UV_EBADF: Bad file descriptor

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#134]
**Server Script**

```php
<?php

require __DIR__ . "/vendor/autoload.php";

Amp\Loop::setErrorHandler(function ($exception) {
    fputs(STDERR, $exception->getMessage() . PHP_EOL);
});

Amp\Loop::run(function () {
    Amp\Socket\listen("tcp://127.0.0.1:1337", function (Amp\Socket\Socket $socket) {
        $generator = function (callable $emit) {
            while (true) {
                $message = yield "\n";
                $emit($message);
            }
        };

        $emitter = new Amp\Emitter;
        $parser = new Amp\ByteStream\Parser($generator([$emitter, "emit"]));

        $promise = Amp\ByteStream\pipe($socket, $parser);
        Amp\Promise\rethrow($promise);
        $promise->onResolve(function () use ($emitter) {
            $emitter->complete();
        });

        $iterator = $emitter->iterate();

        while (yield $iterator->advance()) {
            $message = $iterator->getCurrent();
            yield $socket->write("Received: " . $message);
        }
    });
});
```

**Client Command**

```bash
nc localhost 1337 < /dev/urandom > /dev/null
```

**Behavior**

After pressing `Ctrl + C` in the client, the server reports a bad file descriptor to the loop error handler. Something like that doesn't happen with the `NativeDriver`, but with `UvDriver`.

**Comment by bwoebi** [comment]
UV_EBADF occurs when a resource being polled is closed. So, there must have been some shutdown or close, but the poll watcher still exist?
This is not an amp bug. Maybe a byte-stream or socket bug, I can look again at it tomorrow when being more awake.

**Comment by bwoebi** [comment]
I can't reproduce an UV_EBADF, I either get nothing, or:
```
Failed to write to socket Errno: 8; fwrite(): send of 1261 bytes failed with errno=32 Broken pipe
```

**Comment by trowski** [comment]
I can't reproduce `UV_EBADF` either. I get the same as @bwoebi – nothing or a warning.

It's possible we should be invoking the watcher callback on `UV_EBADF`, which will likely find the descriptor has closed when it is used. Not sure if that's the correct thing to do here…

**Comment by kelunik** [comment]
Both on macOS I guess? I can reproduce it in 100% of all cases I tried.

**Comment by bwoebi** [comment]
I've tried on my Debian VM as well, same behavior as on macOS.

**Comment by bwoebi** [comment]
… okay, I can reproduce it some times. But not always.

**Comment by kelunik** [comment]
You can also run the `amphp/redis` test suite to reproduce it. Fails with `UV_EBADF` in case the TCP stream can't be opened.

**Comment by bwoebi** [comment]
UV_EBADF is always emitted upon POLLERR.
I wonder, when exactly is POLLERR emitted (within epoll)?

**Comment by kelunik** [comment]
See http://stackoverflow.com/a/4150097/2373138

**Comment by trowski** [comment]
So it looks like we should invoke the callback on `UV_EBADF` (and for consistency re-enable the watcher), since it's essentially signaling that the socket has closed.

**Comment by bwoebi** [comment]
I think so. And we shall add a test for that behavior.

**Comment by kelunik** [comment]
Why reenable the watcher? Isn't that inconsistent with other implementations then?

**Comment by trowski** [comment]
Does `libev` or `libevent` disable the watcher? In fact, do they even report errors to callbacks in any way? Perhaps we should just be ignoring status and invoking the callback no matter the status?

**Comment by kelunik** [comment]
Yes, I guess that's consistent with `NativeDriver` then.

**Comment by kelunik** [comment]
@trowski This is fully addressed now, right?

**Comment by bwoebi** [comment]
Yes, it should.
