### ISSUE TITLE
Why is Struct part of the public API?

### ISSUE THREAD

**Issue by joshdifabio** [amphp/amp#140]
While the `Struct` trait seems useful, it is unrelated to amp's stated purpose of being _a non-blocking concurrency framework for PHP applications_. Why is it part of the public API?

**Comment by kelunik** [comment]
Same as `CallableMaker`, because it's useful in other packages. And it's not worth having yet another package.

**Comment by joshdifabio** [comment]
Okay. I don't agree with making the public API larger with distracting, unrelated functionality but I appreciate where you're coming from. Thanks for replying, I'm gonna close this issue now.
