### ISSUE TITLE
uv driver exception on macOS

### ISSUE THREAD

**Issue by umbri** [amphp/amp#143]
getting this:
```
Driver -> Amp\Loop\UvDriver
/home/redis/examples/basic.php:13:
int(42)

Warning: uv_is_active(): passed UVPoll handle is already closed in /home/redis/vendor/amphp/amp/lib/Loop/UvDriver.php on line 258
```

```
<?php

require __DIR__ . "/../vendor/autoload.php";

Amp\Loop::run(function () {
    echo "Driver -> " . get_class(\Amp\Loop::get()) . PHP_EOL;

    $client = new \Amp\Redis\Client("tcp://127.0.0.1:6379");

    yield $client->set("foo", "21");
    $result = yield $client->incr("foo", 21);

    var_dump($result); // int(42)
});
```

Running PHP 7.1.6 on macOS (10.12.5) with UvDriver
Same with NativeDriver no problems
Same with EvDriver not problems

On Ubuntu (16.04) no problems with UvDriver

Can someone please check this ? or this problem is only on my mac ?

**Comment by bwoebi** [comment]
Uhm, you're probably using a different version of php-uv on both targets. Try uv 0.2.2.

**Comment by umbri** [comment]
@bwoebi omg, my bad, sorry

Thank you

**Comment by kelunik** [comment]
@bwoebi Maybe we should warn if UvDriver is used with older versions of UV with known bugs?
