### ISSUE TITLE
Deferred and Emitter are not autocompleted in PhpStorm

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#144]
I don't know why yet, probably due to our performance hack. Auto-Import works fine, but they're not suggested while typing `new Def...`.

**Comment by aaron-hall-7** [comment]
Submitted PR #173 as potential solution for this.

**Comment by cigzigwon** [comment]
How is PhpStorm supposed to adhere to a PHP file that does not pattern match a typical PSR-4 standard?

**Comment by cigzigwon** [comment]
I didn't try it yet but it looks like @aaron-hall-7 has the solution what version of PHP Storm here guys? You need >= 9.5? I think?

**Comment by kelunik** [comment]
@cigzigwon PhpStorm parses the files, they don't need to adhere to PSR-4. It works fine inside `amphp/amp`, but not when it's pulled as a dependency.

**Comment by kelunik** [comment]
Opened https://youtrack.jetbrains.com/issue/WI-38507.
