### ISSUE TITLE
Why not pass values through Iterator::advance()?

### ISSUE THREAD

**Issue by acrylic-origami** [amphp/amp#147]
I'm curious about the motivations to have a dedicated `getCurrent()` method for `Iterator` to return values to the consumer — by itself it feels sort of superfluous and unnatural. I don't doubt there is a deep implementation reason for it, but there doesn't however seem to be a shortage of downsides either:

1. Right now, there is no safe way to handle multiple consumers, since `Iterator` can't discriminate which of two consumers receiving the same `advance` signal will consume the value first;
2. The two errors throwable by `Producer::getCurrent` could be irrelevant in the alternative, because:
  * `advance` could issue reissue [insert termination signal] if the iterator is already completed
  *  there is no longer a timing issue racing against the `advance` promise

3. `Producer`'s `value` queue has to have effectively a dummy element to begin with since `advance` can't pop the element the consumer is waiting for;
4. The iteration syntax could more concise: `while($item = yield $iterator->advance())`
  * I admit this one is somewhat of a personal preference because I really enjoy Hack's foreach-await syntax

Conceptually, I don't see exception handling being the problem, because we could try-catch the `Coroutine` when a generator fails, rather than handling exceptions within the generator. The only reason I can think of is to make room for a termination signal, but here I find Hack tackles it elegantly enough: `AsyncIterator::next()` returns `Awaitable<?(TKey, TValue)>` where `?(TKey, TValue)` is a nullable tuple whose `null` signals the end of iteration. Analogous for the value-only `Amp\Iterator`, something like `advance(): Promise<?[T]>`?

I do have some non-arbitrary interest in this feature, as it's causing me quite a bit of pain trying to implement a library for sharing `Iterator`s. I notice also that this is [a relatively recent development](https://github.com/amphp/amp/blame/master/lib/Iterator.php#L28), but seeing as prior code was refactored _into_ this, I assume I'm just missing the reasoning?

**Comment by kelunik** [comment]
Hey, thanks for writing this up. The reason for this being two methods is the possibility to have `null` values in an iterator. Currently we don't support any keys for iterators, but returning `[$key, $value]|null` would have solved this, yes.

With just values being returned, `while($item = yield $iterator->advance())` doesn't completely work as `[]`, `false`, `"0"`, `0`  also evaluate to `false` in addition to `null`.

Why do you want to share iterators? What's the use case?

**Comment by bwoebi** [comment]
Regarding 1.: you can do an \Amp\some() and look at the key of the resolved promise. Then you know what Iterator resolved its Promise. I haven't had a need for this yet, so can't really estimate whether that must be made easier.

Also, note that it is pretty much equivalent to an API we had previously in Amp v1: https://github.com/amphp/amp/blob/1.x/lib/PromiseStream.php

Regarding `Promise<[value, key]|null>`, I like that idea. It's essentially having you write `while (null !== [$item] = yield $iterator->advance())` and saves you an extra `$iterator->getCurrent()` call (I'd put key as second parameter as more often than not, you don't need the key, just the value). And if there ever is a foreach await possible in some form, this should be easily convertible then.
I just haven't thought about that being an option at all yet...

**Comment by kelunik** [comment]
> while (null !== [$item] = yield $iterator->advance())

Why does that not emit a notice? https://3v4l.org/DrvqK

**Comment by bwoebi** [comment]
What notice did you expect? Array dereferencing null always returns null. That's a feature enabling such syntax. Or how did you expect patterns like `while (list($val, $key) = each($array))` or whatever to work?

**Comment by trowski** [comment]
The `Iterator` interface is meant to be completely un-opinionated about the values that may be omitted. This means that it to allows emitting falsy values while avoiding the pitfalls of PHP's treatment of values such as `"0"` and `[]` as false, even though they may be perfectly reasonable values to emit.

It is trivial to build another interface around `Iterator` that only has a single `advance()` or `next()` method that resolves to a value or `null`.

```php
class AsyncTraversable {
    private $iterator;

    public function __construct(Amp\Iterator $iterator) {
        $this->iterator = $iterator;
    }

    public function next(): Amp\Promise {
        return Amp\call(function () {
            if (yield $this->iterator->advance()) {
                return $this->iterator->getCurrent();
            }

            return null;
        });
    }
}
```

As suggested above, iterators could have emitted `[value, key]` pairs to avoid the falsy issue. I have never once found a need for keys with an async iterator, so the thought never occurred to me, but overall I think I like the idea. Something to consider for 3.0 at this point… or we could simply choose a different name and introduce it in a 2.x release along side `Iterator`.

An `Iterator` should be thought of as an async generator. In the same way values from `Generator` instances can only be consumed once in a single location, so to is true of `Iterator` values. A wrapper that produces it's own `Iterator` instances can allow for any number of iterators to exist for a single parent iterator. [This gist](https://gist.github.com/trowski/0985a54358a890b2090176420160af16) has a quick example of what a class might look like that consumes values from an iterator and emits them on any number of other iterators.

**Comment by acrylic-origami** [comment]
I'm trying to create ReactiveX behavior in Amp in order to port a [Hack streaming library of mine](https://github.com/acrylic-origami/HHReactor) into [PHP](https://github.com/acrylic-origami/AmpReactor). The relevant behaviors here are cold and hot observables and connectable observables which, above allowing more than one consumer, let consumers also control buffering and some aspects of timing. 

<sup>The ReactiveX language is a bit imprecise to discuss iterators because Observables are in callback land. I'm really going for [InteractiveX](https://www.infoq.com/news/2011/07/Ix) sharing behaviors, known as memoize, publish and share (explained by Bart de Smet [here](https://channel9.msdn.com/Shows/Going+Deep/Bart-De-Smet-Interactive-Extensions-Ix) appox. 44:30 in).</sup>

Surprisingly, it's the "hot" Iterable case, where no items are duplicated, that's posing the most problems. Mostly due to point 1 too. @bwoebi, I should clarify I don't mean one consumer identifying which iterator produced a value. Rather, when one producer giving the same `$this->waiting` promise to many consumers, most of them will be unhappy when they're not the first to call `getCurrent` and it blows up in their faces.

I thought that I could get away with using advance-getCurrent internally for my library, but some features, like balancing items between consumers, could be tackled so much more elegantly with some stronger guarantees about when the consumers receive values off the buffer. I do agree that the virtually all these behaviors are just a wrapping class away (thanks @trowski for actually writing those out!). In the process of writing this library, I'm just realizing how tantalizingly close the existing implementation is to allowing sharing and buffering all on its own, and so in part I'm wanting to know if writing these behaviors myself goes against some deep underlying rationale.

**Comment by kelunik** [comment]
@acrylic-origami Can we close this issue?

**Comment by acrylic-origami** [comment]
@kelunik Yes. Thanks for the insights! I'd like to be in the know if this ever becomes a serious consideration for a future release.
