### ISSUE TITLE
This domain name expired

### ISSUE THREAD

**Issue by Runrioter** [amphp/amp#149]
This domain `amphp.org` name expired.

**Comment by shtse8** [comment]
Yes, I can't read the documentation now. Please help.

**Comment by kelunik** [comment]
Yes, we're aware. It's not really expired according to the interface, but somehow pointing to the wrong nameservers.

You can read the documentation in the `./docs` directory of every package in the meantime, sorry about that.

**Comment by bwoebi** [comment]
Tracking bug: amphp/amphp.github.io#19

For now, until this is resolved, please view the docs markdown pages directly: https://github.com/amphp/amp/tree/master/docs

**Comment by kelunik** [comment]
The domain has been restored back to normal several days ago.
