### ISSUE TITLE
How to get a promise state?

### ISSUE THREAD

**Issue by shtse8** [amphp/amp#151]
I have a recursion. But I want resolve the the promise at the first recur. But once I try to resolve the promise second time. an error is throw as follow.
```
Uncaught Error: Promise has already been resolved, define const AMP_DEBUG = true and enable assertions for a stacktrace of the previous resolution. 
```
So I want to detect the promise state to prevent resolving the promise twice. 
Or, I just catch that error instead?

**Comment by kelunik** [comment]
If you need it, just keep that state yourself, e.g. null the reference to the deferred and always check the reference for not being null before resolving.
