### ISSUE TITLE
Is it possible to make work Amp\Promise\wait() in async context?

### ISSUE THREAD

**Issue by torinaki** [amphp/amp#152]
My question is following. Is it possible to make work Amp\Promise\wait() in async context? Or if it is impossible is there any other solution to wait Promise w/o yield'ing and event loop work blocking.
Idea behind this question is following. I'm trying to find way how to implement Amp support for such popular libraries like Doctrine and Ruflin's Elastica library by implementing MySQL driver based on https://github.com/amphp/mysql and Elastica transport based on https://github.com/amphp/artax .

The main issue is that the only way how I can wait Promise inside in async context is to bubble promise using "yield" statement until Event Loop context. In this case I have to add "yield" statement everywhere in library code where I want to get value from method that eventually became a generator:
```
$response = yield call($generatorMethod, ...$arguments);
```
Fortunately not all code line need to be adjusted. When you directly use returned value from generator method call you don't need change anything:
```
return $this->generatorMethod($argument1, $argument2);
```

I guess I want to find some kind of syncronization functionality like Go lang has:
https://nathanleclaire.com/blog/2014/02/15/how-to-wait-for-all-goroutines-to-finish-executing-before-continuing/#the-canonical-way

**Comment by staabm** [comment]
you can combine promises with all[1] and wait[2] for it to get something like is described in the mentioned article

[1] https://github.com/amphp/amp/blob/05491a57c98bffdd0728477819c2211c0802daeb/lib/functions.php#L269
[2] https://github.com/amphp/amp/blob/05491a57c98bffdd0728477819c2211c0802daeb/lib/functions.php#L139

**Comment by torinaki** [comment]
@staabm `wait` function is suitable only for sync context not for async:
https://github.com/amphp/amp/blob/05491a57c98bffdd0728477819c2211c0802daeb/lib/functions.php#L128

**Comment by torinaki** [comment]
@staabm also `wait` function creates additional Event Loop inside existing one:
https://github.com/amphp/amp/blob/05491a57c98bffdd0728477819c2211c0802daeb/lib/functions.php#L151
My goal is to use existing loop

**Comment by kelunik** [comment]
> The main issue is that the only way how I can wait Promise inside in async context is to bubble promise using "yield" statement until Event Loop context.

Correct, promises are viral.

> also wait function creates additional Event Loop inside existing one

No, it runs the previous event loop. `wait` isn't magic, it's just a small helper wrapper around `Loop::run` that stops the loop as soon as the passed promise is resolved.

The only way to "wait" for a promise to resolve, is really running the event loop until the promise resolved, there's no way around that.

You could use `wait` in an async context, but each such call will increase the call stack until it explodes.

**Comment by torinaki** [comment]
@kelunik thanks you. Seems my original issue is realed to Amp version 1 when I get following fatal error:
```
PHP Fatal error:  Uncaught LogicException: Cannot tick() recursively; event reactor already active
```
Amp version 2 allows me to use `wait` inside async context. I see your point about call stack explosion. Of course `wait` is only workaroud in this case until `yield` will be implemented.

**Comment by torinaki** [comment]
@staabm sorry, you was right :)

**Comment by torinaki** [comment]
Now clear. Question answered
