### ISSUE TITLE
Incorrect assumption assertions are always enabled

### ISSUE THREAD

**Issue by far-blue** [amphp/amp#157]
The amp codebase behaves differently when assertions are enabled in ways beyond just using assert() - such as changes to class inheritance. The codebase allows invalid behaviour when assertions are disabled and there is an implicit assumption that developers will always be developing in a php environment where assertions are enabled. If developers don't enable assertions then invalid behaviour is allowed in the code which might then break in a different environment.

The assumption that all developers will have assertions enabled is false because the default installs of php in all operating system environments is production mode (with assertions disabled). The resulting developer experience is pretty poor and is likely to cause more issues for developers new to Amp than benefits.

Because the amp codebase effectively requires assertions to be enabled in order to safely use it for development, I suggest a warning be output to stdout when the run loop is enabled when assertions are disabled, unless the warning is explicitly disabled in code. There are already similar warnings in Aerys regarding debug mode and assertions.

**Comment by bwoebi** [comment]
That may indeed be a problem.

With warning to stdout you probably mean `trigger_error()` with `E_USER_WARNING`?

I'm not sure whether that's the right solution … Perhaps someone else has good opinions on this?

**Comment by kelunik** [comment]
I guess we should just disable that optimization by default and use `defined("AMP_OPTIMIZE_DEFERRED") && AMP_OPTIMIZE_DEFERRED` instead of assertions.

**Comment by bwoebi** [comment]
I'd be totally generic by default and add an constant `AMP_OPTIMIZATIONS`. Then we can have `defined("AMP_OPTIMIZE_DEFERRED") ? AMP_OPTIMIZE_DEFERRED : (defined("AMP_OPTIMIZATIONS") && AMP_OPTIMIZATIONS)`. To have a super-switch turning all optimizations on/off, while still allowing particular optimizations to be enabled or disabled individually.

That super-switch constant shall then also be used in other amp projects.

We even might require that constant to be defined in applications or trigger a warning then - not sure about that.

**Comment by kelunik** [comment]
@trowski What's your opinion on that?

**Comment by trowski** [comment]
I like the idea that @bwoebi proposed above, particularly about issuing a warning if `AMP_OPTIMIZATIONS` is not defined so that users are aware that performance can be improved in production by defining the constant. I'll put together a PR in the coming days.

**Comment by kelunik** [comment]
@trowski I don't like to throw a warning by default.

**Comment by bwoebi** [comment]
@kelunik I agree, we should rather throw an exception there.

**Comment by kelunik** [comment]
@bwoebi WTF. No. Optimizations should just be off by default. I don't want to care about such things if just starting with a new thing.

**Comment by bwoebi** [comment]
No, I'm serious.

If we enforce it, people have _one_ fixed place in their app, where they define that constant. Additionally it raises awareness of the debug mode and tells people what debugging possibilities they have.

**Comment by kelunik** [comment]
This is not about debugging possibilities, it's about performance possibilities.

As said, I very strongly disagree.

**Comment by bwoebi** [comment]
Well, it goes in both directions. Perhaps @rdlowrey also has some opinion on this.

**Comment by trowski** [comment]
Merged https://github.com/amphp/amp/commit/be3ae73a451e933d584ce9d9906776a11450c87a, closing this issue. `Deferred` and `Emitter` now have a single definition.
