### ISSUE TITLE
Nested event loop runs

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#158]
Nested event loop runs had a quite heated discussion in `async-interop`. Now I had an issue with nested runs, because `Loop::stop()` of `Amp\Promise\wait()` stops all runs, so an `Amp\Promise\wait()` inside `Amp\Loop::run()` is definitely a bad idea, but it might happen. Maybe we should protect against that and at least issue a warning?

**Comment by iamsyh** [comment]
I'm having this same issue actually. I'm using parallel to spawn a set of amp-processes which then spawns some more processes of its own. The second Loop::run() (in the sub-process of process) without waiting for all resolved promises.

**Comment by kelunik** [comment]
The fiber-version will solve this.
