### ISSUE TITLE
Bottleneck analysis

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#161]
For enterprise applications it is very important to know if there are bottlenecks in a system. In case of AMP this means blocking tasks.

With a slightly modified loop driver it would be easy to identify and report blocking tasks. To achieve that, each executed watcher has to be measured. This only is not sufficient to debug an issue. It is necessary to identify the watcher in a reasonable way. The watcher needs more context. A backtrace of the point when the watcher was added would be helpful but slow. A faster ways would be to add a context to every watcher. For Aerys this could be the current request.

Adding context information to every callback would a) be very costly during development b) break the interface. It would be easier to set a context globally e.g. Loop\Context::set($request). A reference to the current context (an arbitrary object or object container) can be stored with every watcher when the watcher is being enqueued and restored before the watcher is being executed.
So every watcher always has a context and is able to report that (not only) when blocking tasks are detected.

In a parallel / concurrent system a global (static) context would be an issue and not reliable / consistent but as PHP in general and AMP in special is a single threaded / non-current runtime this works perfectly.

By measuring each watcher it is also possible to report the overall utilization and responsiveness of the loop. This helps to make decisions when to add more workers or machines:
`Utilization = Time elapsed / Time spent executing watchers`
This metric can be fetched and e.g. reported to a time series DB by the application using AMP.

**Comment by bwoebi** [comment]
There's one small library for this: https://github.com/kelunik/loop-block

Is that achieving what you need?

**Comment by kelunik** [comment]
@bwoebi While `kelunik/loop-block` works, it's quite expensive to run it often. I'd be better to run it every tick, but that's not possible to implement outside the driver, because it has to schedule two ticks that immediately result in another tick instead of idling in `stream_select`.

**Comment by kelunik** [comment]
Associating context will be much easier with [Revolt's v0.2.0](https://github.com/revoltphp/event-loop/releases/tag/v0.2.0) release, which adds `FiberLocal`. Wrapping callbacks to measure their execution time will also be much more helpful now.
