### ISSUE TITLE
Iterators and garbage collection

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#168]
I'm currently thinking about https://github.com/amphp/aerys/issues/109 and iterators. What happens if one responder returns a response with an `IteratorStream` and keeps an `Emitter` to streaming some events. If a middleware later replaces that stream without consuming it, the emitter will be stuck waiting for the backpressure to resolve, no?

An iterator not being consumed any further might also happen in other cases, which leaves the emitter without any notice to clean up, no?

**Comment by trowski** [comment]
@kelunik It seems we need to take more care to have destructors on objects relying on iterators (such as `IteratorStream`) to consume the remaining values from the iterator to avoid the problem you described. I recently added such a destructor in the postgres lib to consume remaining tuples in unbuffered result sets: https://github.com/amphp/postgres/blob/master/lib/PqUnbufferedResult.php#L41-L45

Another option may be adding a `dispose()` method to iterators to indicate the consume is no longer interested in the values emitted. Back-pressure promises are currently resolved with null. However, we could resolve with a bool to indicate if the consumer has disposed – true if more values are desired, false if the iterator has been disposed.

**Comment by kelunik** [comment]
Iterators have been removed in v3 due to these issues and will be replaced with pipelines: https://github.com/amphp/pipeline
