### ISSUE TITLE
amp for laravel~

### ISSUE THREAD

**Issue by zuohuadong** [amphp/amp#169]
If I use the Laravel framework, is it a big change?

**Comment by kelunik** [comment]
That depends entirely what you're trying to do. Which components do you plan to use?

**Comment by zuohuadong** [comment]
1. I want it to replace nginx or apache.
2. Use wesocket / socket / TCP server and client

If you only use these, the sense of performance and Nginx gap will be great.
If you use asyn IO and asyn SQL, I need to change the Laravel framework, not sure how much change will be.

**Comment by zuohuadong** [comment]
If it can be compatible with Laravel just fine.

**Comment by kelunik** [comment]
The biggest problem will be blocking I/O, which is any I/O that Laravel does. If you don't use Laravel's I/O functions, everything should be fine. But I guess these are a lot of things that can't really be used.

**Comment by kelunik** [comment]
I'm closing this due to the lack of activity. If you have further questions, just respond, we can always re-open the issue.

**Comment by deniztezcan** [comment]
For encryption I've to update about 4M sql rows; Will it be possible to speed it up with AMP?

**Comment by zardilior** [comment]
I would like to make a query, and send it as an email through excel. As the query is huge, I would like for . a response to be done and for the process to run in parallel

**Comment by kelunik** [comment]
@zardilior You want to decouple the report generation from the request triggering it? The best solution is probably to use a job queue like Beanstalkd for that between your web request handler and a long running worker process generating the report as soon as one is in the queue.
