### ISSUE TITLE
Not possible to cleanly shutdown EventDriver

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#177]
When a loop is set, the old loop cannot be cleanly shutdown.
Tested with EventDriver, the driver is not destructed if there are registered watchers. The API does not allow a manual shutdown. This also leads to a memleak as the object is never GCed.

See here for a test and a change that fixes the issue (quick + dirty):
https://gist.github.com/brstgt/0a83963136436ef5e266c1d807e513c4

**Comment by kelunik** [comment]
@trowski Should https://github.com/amphp/amp/commit/22eb14d7361c40dcca932bb34756b7cc78e73b48 also be applied for `EventDriver` then?

**Comment by trowski** [comment]
@kelunik Probably just to be safe here, I haven't used that driver much so I have no idea if it has the same behavior. @brstgt's gist also includes a similar null check and free for the loop handle, so perhaps that's needed as well.

**Comment by kelunik** [comment]
@trowski @brstgt Can this issue be closed?

**Comment by brstgt** [comment]
No. Eventdriver is still leaking without an explicit destroy method!!

Niklas Keller <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
21:47:

**Comment by kelunik** [comment]
Opened https://bitbucket.org/osmanov/pecl-event/issues/50/garbage-collection-issue.

**Comment by kelunik** [comment]
Closing, as this issue is a bug in the event extension and will be solved there.

**Comment by brstgt** [comment]
Gr8 job, thanks!
