### ISSUE TITLE
Promise documentation examples

### ISSUE THREAD

**Issue by shrikeh** [amphp/amp#178]
Hi,

Wondering if you can help. I have been trying to use the `artax` and `redis` libraries to create a system for cached lookups (look in Redis, if not there, go find it from these external services).

The problem is the idea of what is "OK" for `onResolve()`. Both the artax promise and the redis promise resolve with a result, rather than an error, if a key does not exist in Redis, or a 404 is returned from one of the external APIs. Ideally, a found result would be ideal, as this would allow the use of `\Amp\Promise\first` (I don't care if Redis cache returns first or the remote API, I just want the result quickly).

As both are returning with "good" results (in that both libraries treat connecting as success, irrespective of the result), my thought was that I should wrap them individually with another Promise that can `fail()` based on interrogating their payloads. However, it doesn't seem clear to me how to stack these; the role of the `Deferred` library in this is unclear.

**Comment by kelunik** [comment]
Hey,

Just a note: `onResolve()` shouldn't be used directly in 99% of all cases, as coroutines are a better way of consuming promises without callbacks.

In your case you probably want both promises to resolve to the same type, so you can use `Amp\Promise\first()` as you correctly guessed. You can use exceptions for that.

```php
function fetchFromCache(...) {
    return Amp\call(function () use (...) {
        $result = yield $redisClient->...();

        if (!$result) {
            throw new ItemNotFoundException;
        }
        
        return $result; // you probably want to decode it, too?
    });
}
```

Another way would be using `onResolve()` and `Deferred`:

```php
function fetch(...) {
    $deferred = new Deferred;
    $complete = 0;

    $onResolve = function () use ($deferred, &$complete) {
        $complete++;

        if ($error) {
            if ($complete === 1) {
                return; // ignore failure if other operation is pending
            }

            $deferred->fail($error);
        } else {
            if ($complete === 1) {
                // Only resolve, if we're the first one succeeding
                $deferred->resolve($result);
            }
        }
    };

    fetchCache(...)->onResolve($onResolve);
    fetchHttp(...)->onResolve($onResolve);

    return $deferred->promise();
}
```

**Comment by shrikeh** [comment]
Many thanks, that's really helped and also made my repository much clearer.

**Comment by kelunik** [comment]
I'm glad to hear that. :+1:
