### ISSUE TITLE
Remove export-ignore for examples?

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#184]
See https://twitter.com/ivanjaros/status/934019650425376768. Maybe it's better to remove `examples` from `export-ignore`?

**Comment by staabm** [comment]
IMO someone who needs the examples, will likely also benefit from docs and tests.

those should clone/prefer-source instead of relying on distribution packages

**Comment by kelunik** [comment]
Sure, but some people like using GitHub's download button, which uses the `git archive` based version.

**Comment by staabm** [comment]
in case you like to support the "download button" you should add example/docs/tests back. 

IMO its not worth it, the packagist/distribution use-case has far more weight then the download button

**Comment by bwoebi** [comment]
As @staabm says, either ignore them all or none.

I'm personally not concerned about the size of the tests, examples etc. and wouldn't object to ignoring nothing. Basically: I don't care as long as it's either all or none.

**Comment by kelunik** [comment]
I'll close this for now. If someone has something to add, please speak up here.
