### ISSUE TITLE
Php-cs-fixer to auto add \ for php builtins

### ISSUE THREAD

**Issue by staabm** [amphp/amp#185]
Would be cool to have a php-cs-fixer which auto adds \ for php bultin calls, so we dont need to do the tedious task

As this is usefull for hot path e.g. bootstrapping logic in a lot of libs/components/frameworks this might even lbe usefull outside amp context

**Comment by staabm** [comment]
Ohh da gibts schon tools für sehe ich gerade:

> There are multiple tools to achieve this:
https://github.com/nilportugues/php-backslasher
https://github.com/Roave/FunctionFQNReplacer
https://github.com/kelunik/fqn-check
https://github.com/FriendsOfPHP/PHP-CS-Fixer (native_function_invocation )

**Comment by kelunik** [comment]
PhpStorm already does that automatically for me, but we can totally add the `native_function_invocation` rule to our `.php_cs.dist`. Want to provide a PR?
