### ISSUE TITLE
Rewrite extension installation scripts for Travis

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#193]
See #192 for reference, which fixes the script for `ev`.

Actually, these should probably just use `set -x` at the top.

**Comment by Ttone123** [comment]
https://github.com/amphp/amp/issues/193#issue-283309922

**Comment by kelunik** [comment]
Fixed via https://github.com/amphp/amp/commit/4d849191e59481666600ef8b48cf3a88e6898564.
