### ISSUE TITLE
Error when file handles are used with loop watchers

### ISSUE THREAD

**Issue by trowski** [amphp/amp#201]
Using file handles with `Loop::onReadable()` and `Loop::onWritable()` does not work as expected since file ops are blocking and can lead to unexpected behavior with `stream_select()` on Windows: https://github.com/amphp/socket/issues/52. Perhaps we should throw when a file handle is given to one of these methods, suggesting use of `amphp/file` instead?

**Comment by kelunik** [comment]
This is a no-go. STDIN is a file handle on Windows and blocking that makes STDIN unusable on Windows.
