### ISSUE TITLE
Recursive delay() never complete

### ISSUE THREAD

**Issue by Bilge** [amphp/amp#203]
I implemented a simple scheduler to avoid too many concurrent HTTP calls. It works, except the main loop never terminates because the `delay()` calls don't finish normally.

My code looks something like this:

```php
    public function __construct()
        Loop::run(function () use ($appList) {
            $this->scheduleRequests(null, $appList);
        });

        // Never gets here.
        echo 'Compelted';
    }

    public function scheduleRequests(?string $watcherId, Generator $appList): void
    {
        while ($appList->valid() && $this->activeRequests < self::MAX_REQUESTS) {
            $app = $appList->current();

            $this->request('http://example.com', $app);

            $appList->next();
        }

        // This seems to never complete normally.
        Loop::delay(100, [$this, __FUNCTION__], $appList);
    }

    private function request(string $url, array $app): void
    {
        ++$this->activeRequests;

        $this->client->request($url)->onResolve(function ($error, $response)  {
            --$this->activeRequests;
            // ...
        }
    }
```

Every request is dispatched and every request completes and it never exceeds the `MAX_REQUESTS` threshold, so the code works exactly as intended, except that *Compelted* will never be printed on Windows 7 x64.

**Comment by kelunik** [comment]
You need a condition around your timer, e.g. check if the generator is still valid.

**Comment by Bilge** [comment]
Oh, yeah, that's a bit embarrassing, isn't it. Since you've already read the code, can you comment on whether this is the correct approach to this sort of thing?

**Comment by kelunik** [comment]
It's one possible approach of many. If I had a lot of requests to do and needed to restrict the concurrency, I'd probably just create X coroutines that do the job. The advantage of that is, that new request will immediately be started once a response is finished.

```
$queue = /* generator */;
$http = new Amp\Artax\DefaultClient;

for ($i = 0; $i < MAX_REQUESTS; $i++) {
    $coroutines[] = Amp\call(function () use ($queue) {
        while ($queue->valid()) {
            $uri = $queue->current();
            $queue->next();

            $response = yield $http->request($uri);
            // do something with the response
        }
    });
}

Amp\Promise\wait($coroutines);
```

**Comment by Bilge** [comment]
I don't think that does the same thing, though, does it? How is that preventing more than `MAX_REQUESTS` being active at once? It looks like it just prevents the *total* number of requests from being more than `MAX_REQUESTS` rather than just the total *concurrent* number.

**Comment by kelunik** [comment]
`for ($i = 0; $i < MAX_REQUESTS; $i++)` creates basically `MAX_REQUESTS` "threads" and those do the requests sequentially, note the `while` inside the coroutine.

**Comment by Bilge** [comment]
Oh, I see. That's a very efficient specialized implementation for max threads, but it wouldn't be flexible enough to accommodate a different throttling mechanism such as maximum requests per time period (e.g. second/minute). I wanted to move towards writing a general purpose scheduler that accepts a `Throttle` object with an interface like the following.

```php
interface Throttle {
    public function isThrottled(): bool;

    public function notifyRequestMade(): void;
}
```

Throttle implementations can be notified when requests are made and then decide whether the scheduler needs to throttle further requests. In this way, we could have a `Throttle` implementation for max concurrent requests or max requests per minute, depending on the user's requirements.

I believe the code I originally wrote could be easily adapted to accept a `Throttle`, by replacing `$this->activeRequests < self::MAX_REQUESTS` with `!$throttle->isThrottled()`, but I cannot see a way to adapt your implementation the same way. Of course, my code sucks because of the hard-coded 100ms timeout so I'd be interested in a better generic solution that could work with `Throttle`s.

**Comment by kelunik** [comment]
@Bilge The link you're missing is basically when to start new requests. Currently you have a fixed timer that checks for the condition. For a fixed concurrency limit, you can start a new request as soon as another request is done.

I had an interface somewhere that used `Amp\Iterator` + such an interface, but not sure whether I made a package out of it.

**Comment by staabm** [comment]
@Bilge couldn't you take some inspiration from https://github.com/amphp/parallel/blob/master/lib/Worker/DefaultPool.php ?

**Comment by Bilge** [comment]
>For a fixed concurrency limit, you can start a new request as soon as another request is done.

Yes, I see that, and I understand your code now. But I don't think your code is adaptable to a time-based concurrency limit, is it?

**Comment by kelunik** [comment]
@Bilge Yes, it's not.

@staabm No, that doesn't really help here.
