### ISSUE TITLE
Multiple concurrent event loops

### ISSUE THREAD

**Issue by Bilge** [amphp/amp#204]
I understand that when I want to work async I need to work within an event loop, e.g. `Loop::run()`. However, is it possible to have two such loops running concurrently, or perhaps, have a new one begin whilst an existing one is paused?

This is really a two-part question. Before getting back to that, I'd like to understand if it's possible to wrap up an event loop that dispatches a series of async requests inside a generator that can be paused. That is, can I create a generator that will spit out up to 50 requests but if I only iterate it 10 times, I'll only get back the 10 that completed first (not necessarily the first 10 that were dispatched)?

If yes, the second part of the question is that which I posed initially: with this generator still paused (at a `yield`) after outputting some (but not all) of its requests, and thus still keeping its event loop open, can I now begin a separate event loop and do something similar, i.e. dispatch more requests in the second event loop?

**Comment by kelunik** [comment]
It doesn't make sense to run two event loops concurrently, no. That will just hog your CPU. But you can run the event loop, stop it, and continue to run it later, see also `Amp\Promise\wait()`.

**Comment by Bilge** [comment]
OK let's take a step back and ask what I really want to ask instead of being a victim of the XY problem.

My library currently serves a generator to consumers which they can use to iterate some or all of its results. Each iteration may cause a synchronous HTTP request to populate the current result, and sometimes, additional results. The specific relationship between the generator iteration and the HTTP request changes depending on the behaviour of the HTTP endpoint and generally fits one of these models:

* The entire results set is loaded before the first yield, therefore iteration is independent of requests.
* The entire results set is loaded when the first result is yielded, therefore a request is only made when the first result is accessed.
* Results are paginated at the server, so a request is made every time we run out of results from the previous request (i.e. every *n* iterations, where *n* is page size).
* An HTTP request is made on every iteration.

Can any or all of these models be adapted to serve the same results using asynchronous HTTP requests?

**Comment by kelunik** [comment]
I'd use a [`Producer`](https://amphp.org/amp/iterators/#producer) for that instead of a "normal" generator.

```php
$producer = new Producer(function (callable $emit) use ($http) {
    do {
        $url = "...";
        $response = $http->request($url);
        $users = json_decode(yield $response->getBody());
        foreach ($users as $user) {
            yield $emit($user);
        }
        $url = $response->getHeader("next");
    } while ($url !== null);
});

while (yield $producer->advance()) {
    $user = $producer->getCurrent();
    // abort at any time here...
}
```

**Comment by Bilge** [comment]
So is it no longer possible to use normal generators? I was hoping to provide a similar API for sync and async, so it would be easy to switch between the two code paths, making it easy to compare and contrast the two approaches, but if we must use custom iterators this falls down at the first hurdle.

**Comment by kelunik** [comment]
@Bilge Sure, that's still possible, but you'll have to return a promise at every point and the consumer needs to await that. `Amp\Iterator` allows one code-path, the consumer just needs to wrap promise returns in `Amp\Promise\wait()`.
