### ISSUE TITLE
Calling promises running sync instead of async

### ISSUE THREAD

**Issue by zelin** [amphp/amp#207]
I am trying following code, i want to run my functions async, however the for loop that display 1-10000 print values after printing values of sendNotificationsFromEntries. Doesn't seem to be running async. What am i missing?

```
static::sendNotificationsFromEntries($entries);
for($i = 0 ; $i < 100000; $i++)
            echo $i;

function sendNotificationsFromEntries($entries)
{
        Loop::run(function () use($entries)
        {
              $output = yield static::callAysncFunc($value);
              // do a small work on output and 
             echo json_encode($output)
        });
}


private static function callAysncFunc($tokens)
    {
        $deferred = new Deferred();
        Loop::run(function () use ($deferred, $tokens)
        {
            $result = doSomeHeavyLifting();
            $deferred->resolve($result);
        });
        return $deferred->promise();
}
```

**Comment by kelunik** [comment]
`Loop::run()` will block and run the event loop. You need to put `Loop::run()` around your entire application, not inside specific methods.

**Comment by zelin** [comment]
can you modify my code because i am not getting how can i put it over entire application and then get results

**Comment by kelunik** [comment]
```php
<?php

Amp\Loop::run(function () {
    $promises[];
    for ($i = 0; $i < 1000; $i++) {
        $promises[] = someAsyncCall();
    }

    yield $promises;
});
```

Note that you probably don't want to make 1000 calls to `someAsyncCall()` like that, but instead process the data in reasonable chunks, e.g. 10 at a time.

If your `doSomeHeavyLifting()` method blocks (like it seems), your code won't really run concurrently, because `doSomeHeavyLifting()` blocks everything else. You'll have to use non-blocking I/O instead of the traditional blocking I/O function calls, so no `file_get_contents()` / blocking HTTP requests / `sleep()` / …

**Comment by zelin** [comment]
some customised curl and stream_context_create . That is what i want to do, run these things so these calls wont block the other code. So after customising my above code i am doing this now,

```
    $bot->callMainFunc();
    while($i > 1)   /// Test function to check if its blocking or not.
    {
       $i = $i + 1;
       $x = $i % 1000000;
       if($x == 0)
       {
          echo $i. "\n";
          echo json_encode($bot->getResponses()). "\n";
        }
    }

```

The main function i want to implement async call is 
```
callMainFunc()
{
         $promises = array();
        foreach ($entries as $key=>$value)
        {
            $promises[] = static::setupNotificationForEntry($key, $value);
        } 
        
        yield $promises;
}
setupCallForEntry($key, $value)
{
    $deferred = new Deferred();
    Loop::run(function () use ($deferred, $key, $value)
    {
            $mainOutput = // call either a curl or stream context or do some processing on old results;
            static::addToResponse($mainOutput);
            $deferred->resolve($mainOutput);
     });
     return $deferred->promise();
}

```

If you are saying http blocks the promises then how can i implement async calls. 

Weirdly the above function doesnt give me any error but its not making any calls either

**Comment by kelunik** [comment]
`callMainFunc()` will return a [`Generator`](https://secure.php.net/manual/en/language.generators.php). To run this generator as coroutine, you need to wrap the call in `Amp\call()` or use `Amp\coroutine()` to wrap the callable and then call it.

Curl won't interact nicely with Amp. Instead you can use [Artax](https://github.com/amphp/artax) as an HTTP client. If you want to continue using Curl, you need to move these calls into a separate process, e.g. with [`parallel`](https://github.com/amphp/parallel) or [`parallel-functions`](https://github.com/amphp/parallel-functions), so they won't block.

Your `setupCallForEntry()` still calls `Loop::run()` and returns a `Promise`. As a rule of thumb, nothing in the call stack above `Loop::run()` should deal with promises, only code inside `Loop::run()`.

**Comment by zelin** [comment]
okay, i'll do all above, however what about stream_context_create, is amp going to have a problem with that too?

**Comment by kelunik** [comment]
Not with the `stream_context_create()`, but rather with blocking socket operations. You have to set the socket to non-blocking and use `Amp\Loop::onReadable()` and `Amp\Loop::onWritable()` to get notified when data on the socket is available. You can use [`byte-stream`](https://github.com/amphp/byte-stream) or [`socket`](https://github.com/amphp/byte-stream) for a nice abstraction, so you don't have to deal with the event loop and watchers manually.

**Comment by kelunik** [comment]
It seems like all questions have been answered. If not, please respond with further questions, the issue can always be re-opened. :+1:
