### ISSUE TITLE
Adopt "async context" terminology in documentation

### ISSUE THREAD

**Issue by Bilge** [amphp/amp#210]
Trying to learn Amp is difficult for someone new to coroutines and async in the context of PHP. Although I appreciate the work that has been done on the documentation so far, I still find it lacking for giving good background to the topic and its use.

For me, it has been helpful to start thinking about the "async context". It seems to me that in Amp, in order to do anything with async you must be in an *async context*, otherwise async calls will fail with often obscure and unhelpful errors. Generally, this means starting the event loop with `Loop::run` (I remain unclear whether there are other methods). Managing the boundary between sync code and async code, and knowing which context you're in, seems to be critical to writing successful async applications and yet this concept is not very well explained anywhere presently.

I propose adopting the *sync context* and *async context* terminology throughout the documentation, where appropriate, and give an introduction to the library phrased in these terms. Make it clear exactly which methods can be used to enter and exit the async context, and which methods will start an async context implicitly (such as `Amp\Promise\wait()`). I suggest it's also important to mention that nested async contexts are invalid.

**Comment by kelunik** [comment]
I guess things will be much easier to understand with fibers instead of generators everywhere. :smile:

**Comment by Bilge** [comment]
Probably not, async is only for super big brains 😆
