### ISSUE TITLE
Event loop behaviour for supported yielded types documentation

### ISSUE THREAD

**Issue by Bilge** [amphp/amp#211]
It seems the event loop is the asynchronous heart of Amp, and scheduling tasks by `yield`ing things to it is core to its theory of operation. And yet, there appears to be no documentation as to *what* you can `yield` nor *what happens* when you do this, and that presents a huge burden to understanding what Amp is all about.

One can quickly glean that yielding promises is one possibility: when you yield a promise, Amp will return the successful result once it's available. But what happens if you yield a promise that errors? What else can be yielded besides promises? There appears to be no documentation for this.

Browsing further [examples in the documentation](https://amphp.org/amp/promises/combinators) reveals *arrays* can be yielded to the event loop. A code comment reads:

```
        // magic combinator sauce to flatten the promise
        // array into a single promise.
        // yielding an array is an implicit "yield Amp\Promise\all($array)".
```

The useful part of the comment is the third line that reveals yielding an array causes an implicit `Amp\Promise\all` to be performed on the array; but this is absolutely the wrong place to be introducing core event loop behaviour, since this page purports to be about *promises*, not the event loop.

I propose having a page or section dedicated to all the different types the event loop supports, how it handles them, and *why* it behaves that way&mdash;that is, the design reasoning behind it (if not already clear).

**Comment by kelunik** [comment]
`yield` does _not_ schedule things. Creating loop watchers schedules things.

The types `yield` supports are clearly documented [here](https://amphp.org/amp/coroutines/#yield-behavior). Do you think the types need further documentation?

**Comment by Bilge** [comment]
That table is exactly the kind of thing I was looking for, and if it's complete, that's fine. It's just not in the place I expected it to be (*event loop*, rather than *coroutines*).

However, what are *loop watchers?*

**Comment by kelunik** [comment]
https://amphp.org/amp/event-loop/api#timer-watchers + https://amphp.org/amp/event-loop/api#stream-io-watchers ;-)
