### ISSUE TITLE
Fatal error during shutdown

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#212]
I see this pretty frequently in the logs:

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: Amp\Loop::$driver in /www/jaumo/vendor/amphp/amp/lib/Loop.php:264#012Stack trace:
#012#0 /www/jaumo/vendor/amphp/amp/lib/TimeoutCancellationToken.php(32): Amp\Loop::cancel('ijr')
#012#1 [internal function]: Amp\TimeoutCancellationToken->__destruct()
#012#2 {main}#012  thrown in /www/jaumo/vendor/amphp/amp/lib/Loop.php on line 264
```

**Comment by brstgt** [comment]
Yet another one:
```
2018-04-03T07:24:44+00:00 php9 ker: PHP Fatal error:  Uncaught Error: Access to undeclared static property: Amp\Loop::$driver in /www/jaumo/vendor/amphp/amp/lib/Loop.php:107
#012Stack trace:
#012#0 /www/jaumo/vendor/amphp/amp/lib/Internal/Placeholder.php(143): Amp\Loop::defer(Object(Closure))
#012#1 /www/jaumo/vendor/amphp/amp/lib/Deferred.php(36): class@anonymous->resolve(NULL)
#012#2 /www/jaumo/vendor/amphp/byte-stream/lib/ResourceInputStream.php(127): Amp\Deferred->resolve(NULL)
#012#3 /www/jaumo/vendor/amphp/byte-stream/lib/ResourceInputStream.php(168): Amp\ByteStream\ResourceInputStream->free()
#012#4 [internal function]: Amp\ByteStream\ResourceInputStream->__destruct()
#012#5 {main}#012  thrown in /www/jaumo/vendor/amphp/amp/lib/Loop.php on line 107
```

**Comment by kelunik** [comment]
We :heart: shutdown bugs.

**Comment by brstgt** [comment]
I'm sorry :( But a bug is a bug ...

**Comment by trowski** [comment]
I assume this bug is actually in PHP, as of course `Loop::$driver` is declared. We should see if we can work around the bug, but probably fix it in php-src as well.

**Comment by bwoebi** [comment]
It is undeclared when cleaned up during shutdown.

You're at that point really trying to access a property which doesn't exist anymore. Not a bug in php-src.

**Comment by trowski** [comment]
@bwoebi So undefined destruct order is rearing it's ugly head again. How do you suggest we avoid that? It's rather common for destructors to cancel loop watchers.

**Comment by brstgt** [comment]
```if (isset(Loop::$driver)) {
return;
}
```

helps here. The problem is that you don't know the order of destruction. If loop is destructed before objects accessing the loop in d'tors are destructors then you get that one.
This can be caused by stopping the loop before some watchers have finished.

**Comment by trowski** [comment]
@brstgt Yep, that should nicely cover the methods like `cancel` and `disable` that can be ignored during shutdown. What about watcher creation like the second example (which may be just a result of a promise callback cancelling a loop watcher)? Throw in that scenario anyway, just with a better message like "Cannot create loop watchers during shutdown."

**Comment by bwoebi** [comment]
@brstgt What version of PHP are you running? If you are running something inferior to PHP 7.2, please try 7.2 and tell me whethert it still happens.

**Comment by bwoebi** [comment]
@kelunik https://github.com/php/php-src/commit/9a8a1c9da129a72c9bf8f3392f954a9e5ca317ff is 7.2+ only - on elder versions it may still happen.

**Comment by brstgt** [comment]
@bwoebi We run on 7.1.11 - I don't want to update our production system just like that but it's good to know!

**Comment by bwoebi** [comment]
@brstgt At least I strongly guess that's the issue given it happens in a destructor.

From PHP 7.2 onwards it _should_ be impossible to execute any PHP code after destructors are run (unless you use some extension doing shady stuff like calling into PHP code from resource destructors, rshutdown or such). If not, it's indeed a bug in php-src.

**Comment by kelunik** [comment]
The second trace seems to be also a cancelled watcher. https://github.com/amphp/amp/blob/c632e40b03343981db73618df271d53176ac5320/lib/Internal/Placeholder.php#L141-L143 is just created, before something else throws, which I guess is the `Loop::cancel()` inside `free()`.

I hereby propose to go with the `isset()` ignore for PHP < 7.2 then for `disable` and `cancel` and ignoring others such as `enable()`, etc. We might be able to have a better error message, but the actual issue is unsolvable then.
