### ISSUE TITLE
NativeDriver leaks timer watchers

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#220]
`NativeDriver::$timerQueue` has no way to free a watcher that has been cancelled until it times out.
It would be better to store that watcher data in a separate struct and only store watcher ids in `$timerQueue` so the leak gets smaller.

If you have a lot of promises with timeouts the leak can be quite noticeable!

**Comment by kelunik** [comment]
We know and we'll fix it, probably by avoiding the SPL data structure completely.
