### ISSUE TITLE
Uncaught Error: Class 'Amp\Loop' not found in C:\xampp7.1.4\htdocs\amphp\process\examples\basic-command.php:9

### ISSUE THREAD

**Issue by staabm** [amphp/amp#222]
using the latest amp\process I get a exception

```sh
C:\xampp7.1.4\htdocs\amphp\process>C:\xampp7.1.4\php\php.exe examples\basic-command.php
PHP Fatal error:  Uncaught Error: Class 'Amp\Loop' not found in C:\xampp7.1.4\htdocs\amphp\process\examples\basic-command.php:8
Stack trace:
#0 {main}
  thrown in C:\xampp7.1.4\htdocs\amphp\process\examples\basic-command.php on line 8

Fatal error: Uncaught Error: Class 'Amp\Loop' not found in C:\xampp7.1.4\htdocs\amphp\process\examples\basic-command.php:8
Stack trace:
#0 {main}
  thrown in C:\xampp7.1.4\htdocs\amphp\process\examples\basic-command.php on line 8
```

I guess the reason is that there is no proper amphp\amp version for php 7.1 to install and therefore the loop class is missing

```sh
C:\xampp7.1.4\htdocs\amphp\process>php -v
PHP 7.1.4 (cli) (built: Apr 11 2017 20:08:12) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by staabm** [comment]
also reproducible on 7.0

```
C:\xampp7.1.4\htdocs\amphp\process>C:\xampp7_0_13\php\php.exe -v
PHP 7.0.13 (cli) (built: Nov  8 2016 13:45:28) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by kelunik** [comment]
I guess you didn't run `composer install`?

**Comment by staabm** [comment]
I did.

**Comment by staabm** [comment]
hmm after running `composer update` it worked for me.

sounds like a workflow error on my end or a bug in composer itself...

**Comment by sahil70009** [comment]
Very helpful your article sir but I face some error in log-in page please give me solution.
 
Fatal error: Uncaught Error: Class 'Member[Error](https://www.rockmoney.org) ' not found in www.rockmoney.org :4 Stack trace: #0 /srv/disk1/2937386/www/gpass.getenjoyment.net/index.php(17): require_once() #1 {main} thrown in /srv/disk1/2937386/www/gpass.getenjoyment.net/login-form.php on line 4

**Comment by ecairol** [comment]
Make sure you're not missing Composer's autoload:
```
require dirname(__DIR__) . '/vendor/autoload.php';
```

If working from a WordPress plugin:
```
require plugin_dir_path( __FILE__ ) . '/vendor/autoload.php';
```
