### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Amp\Artax\DefaultClient' not found

### ISSUE THREAD

**Issue by sajumani** [amphp/amp#223]
Hi,

**Am getting this error with sample code ... Could you please suggest what am missing ?**  

Fatal error: Uncaught Error: Class 'Amp\Artax\DefaultClient' not found in /usr/share/nginx/html/index.php:18
Stack trace:
#0 [internal function]: {closure}('a', NULL)
#1 /usr/share/nginx/html/vendor/amphp/amp/lib/Coroutine.php(39): Generator->current()
#2 /usr/share/nginx/html/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\Coroutine->__construct(Object(Generator))
#3 /usr/share/nginx/html/vendor/amphp/amp/lib/Loop/Driver.php(70): Amp\Loop\Driver->tick()
#4 /usr/share/nginx/html/vendor/amphp/amp/lib/Loop.php(76): Amp\Loop\Driver->run()
#5 /usr/share/nginx/html/index.php(36): Amp\Loop::run(Object(Closure))

**Comment by kelunik** [comment]
You need to require [`amphp/artax`](https://github.com/amphp/artax) in your project, e.g. by running `composer require amphp/artax`.
