### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by vojtasvoboda** [amphp/amp#227]
Hi all, I'm trying to require this repository to my project, but it contains some submodules which are not included in vendor folder and then I have some broken links:

<img width="211" alt="snimek obrazovky 2018-05-16 v 21 18 28" src="https://user-images.githubusercontent.com/374917/40140502-6e793ca4-5953-11e8-87d7-9fb01227053e.png">

Because of that my CI throwing some errors:

```
/vendor/amphp/sync/docs/asset': No such file or directory
/vendor/amphp/parallel/docs/asset': No such file or directory
/vendor/amphp/parallel/travis/install-pthreads.sh': No such file or directory
/vendor/amphp/file/travis/install-uv.sh': No such file or directory
/vendor/amphp/dns/docs/asset': No such file or directory
/vendor/amphp/socket/docs/asset': No such file or directory
/vendor/amphp/artax/docs/asset': No such file or directory
```

Could you please help me? Is there some command to require this project with all submodules?

Thanks a lot

**Comment by kelunik** [comment]
All `docs/asset` links should be gone with the next releases. Your CI should probably not care about broken links there. The submodule only exists for the documentation and there's no need for it in the vendor directory.

**Comment by kelunik** [comment]
I hadn't close this issue before, but resolved it. If there are new broken links, please report them to the affected repository or directly open a pull request to fix it.
