### ISSUE TITLE
Question regarding phpunit

### ISSUE THREAD

**Issue by twifty** [amphp/amp#228]
I would ask this on stackoverflow, but that site has become very toxic towards niche questions.

I've used `Amp\Socket\ServerSocket` to create a PHP server. This server accepts a client connection, launches a child process (using `Symfony\Component\Process`) and pipes the stdout back over the open socket.

Within phpunit, I mock the `ServerSocket` and place expectations on the `write` method, then within `Loop::run` I invoke the `read` method of my server which would actually be passed sent data from the socket. It looks something like this:

```php
    /**
     * @dataProvider provideRead
     */
    public function testRead (string $input, array $output)
    {
        $this->socket = $this->createMock(ServerSocket::class);
        $this->socket
            ->expects($this->exactly(count($output)))
            ->method('write')
            ->withConsecutive(...array_map(function($entry) {
                return [$this->matchesRegularExpression($entry)];
            }, $output))
        ;

        Loop::run(function () use ($input) {
            $this->interpreter->read($input);
        });

        $this->expectOutputRegex('/.+/');
    }

    /**
     * Provider for {@see testRead}
     *
     * @return array
     */
    public function provideRead (): array
    {
        return [
            'CMD_ARE_YOU_THERE' => [
                static::wrap(CommandsInterface::CMD_ARE_YOU_THERE),
                [
                    static::match(CommandsInterface::CMD_PROCESS_STDOUT, "Poke me again! I dare you!!!\n")
                ]
            ],
        ];
    }
```

It works flawlessly on my local machine, but on Travis the tests sometimes fail.

I've narrowed the failures down to the subprocess created by the server being sent a SIGKILL before it has finished writing to the socket. I'm guessing this is because `Loop::run` is completing before the process.

I'm not sure how to deal with this. In `node` I would wrap the process in a promise and resolve when it completes. Using `amphp` I use `Loop::defer` and check the process' state on each iteration.

The full [code is here](https://github.com/twifty/php-interpreter-service/tree/master/src).

If anybody could point out why I'm getting these random test failures, I will be very grateful.

**Comment by kelunik** [comment]
Using `Loop::defer` in a tight loop to check your process state will hog your CPU. Either use a timer based approach to lower the CPU usage or use https://github.com/amphp/process which is designed to work well with Amp.

Instead of [this](https://github.com/twifty/php-interpreter-service/blob/c25256fa681b6cb47d5e939a69470c17262cc5ee/src/main.php#L16-L19) you can use `Loop::onSignal`.

I'm not sure why your code fails and currently don't have the time to debug it.

**Comment by bwoebi** [comment]
Also: if you want full integration with the event loop, it's preferable to use amphp/process instead of the Symfony process component, which does all heavy lifting of the stdio pipes across operating systems for you.
Then you can definitely also wait for process termination.

**Comment by twifty** [comment]
Thanks for pointing me towards `amphp/process`, I'll swap it out and see if anything changes.

**Comment by kelunik** [comment]
Closing, as there hasn't been any activity. If you have further questions, feel free to respond or create a new issue.
