### ISSUE TITLE
Remove `wait()` from core?

### ISSUE THREAD

**Issue by DaveRandom** [amphp/amp#229]
Following https://github.com/amphp/postgres/issues/11#issuecomment-391995907 and similar/identical mistakes I have seen people make in the past, I wonder if moving `wait()` (and any other tools that are specifically for adapting async code to run within a sync context that I can't think of right now) to a separate lib.

Having this separation, and the requirement to explicitly include an additional component in dependencies, might help avoid these sort of mistakes for new users?

Obviously this would be a significant BC break and couldn't be done until the next major.

**Comment by kelunik** [comment]
I'm going to close this one, as Amp v3 will not have promises anymore, see `ext-async`.
