### ISSUE TITLE
Struggling to get async working

### ISSUE THREAD

**Issue by lvandyk** [amphp/amp#230]
I have been through the documentation as well as examples on Github, tried using deferred and the method below:

```
$result1 = null;
$result2 = null;

Loop::run(function() use (&$result1, &$result2) {
    
    $result1 = yield \Amp\call(function() {
      return SomeWeatherLib::getTemp('Some City');
    });

    $result2 = yield \Amp\call(function() {
      return SomeWeatherLib::getTemp('Some City');
    });
});
```

Is there something I'm missing?

**Comment by bwoebi** [comment]
Is `SomeWeatherLib::getTemp('Some City');` also using non-blocking I/O internally? Otherwise there's quite no point in this.

**Comment by lvandyk** [comment]
Unfortunately its not. Its a single cURL request and returns the response. What are my options then? I need those calls to be done async or it takes too long..

**Comment by PeeHaa** [comment]
Use the [Artax HTTP client](https://github.com/amphp/artax) to make non blocking http requests instead.

**Comment by lvandyk** [comment]
Ok awesome thanks for the feedback. Is there anywhere I can find an example of using a `pool` or `semaphore` lock to avoid too many concurrent requests at the same time?

**Comment by staabm** [comment]
see https://github.com/amphp/artax/tree/master/examples
