### ISSUE TITLE
Some drivers do not handle timeouts correctly for first tick

### ISSUE THREAD

**Issue by andrewmackrodt** [amphp/amp#232]
Experienced this issue while implementing https://github.com/amphp/react-adapter/pull/8; the failure causes for `EventDriver` and `NativeDriver` is due to `$this->now` being set only in the `__construct` and `dispatch` methods, dispatch is called after a tick. `UvDriver` sometimes returns early but that is to do with the extension.

To reproduce add this test case in `Loop/EventDriver.php`:
```php
public function testTimerIntervalBlocksOnFirstTick()
{
    $start = \microtime(true);
    $this->start(function (Driver $loop) use (&$invoked) {
        $loop->delay(1, function () use (&$invoked) {
            $invoked = true;
        });

    });
    $end = \microtime(true);
    $this->assertTrue($invoked);

    // make no strict assumptions about actual time interval.
    // must be at least 0.001s (1ms) and should not take longer than 0.1s
    $this->assertGreaterThanOrEqual(0.001, $end - $start);
    $this->assertLessThan(0.1, $end - $start);
}
```
However, this appears to be intentional behaviour as updating `$this->now` in the drivers causes `testTimerIntervalCountedWhenNotRunning` to fail. Is there a way to support both cases?

**Comment by kelunik** [comment]
I noticed that myself. I have ported the adapter to 0.5 locally, too, but haven't pushed it yet due to the failing tests.

**Comment by andrewmackrodt** [comment]
I've created a PR https://github.com/amphp/amp/pull/233 aimed at resolving this, although as mentioned in it's description, it's a breaking change due to `testTimerIntervalCountedWhenNotRunning`.

**Comment by andrewmackrodt** [comment]
It seems adding `\uv_run($this->handle, \UV::RUN_NOWAIT)` or `$this->dispatch(false)` to `UvDriver::run` before calling the parent also fixes the new test case and those in `amphp/react-adapter` without resorting to using different timeouts. I'm unfamiliar with the uv library to know how to handle this correctly however.

**Comment by kelunik** [comment]
This has been resolved. We update the current time only once per tick and the first time starts with the creation of the event loop. This behavior won't change, at least not until we release v3.0.0, which likely won't have an event loop anymore, but use one built into PHP's core or an extension.
