### ISSUE TITLE
Swoole Adapter

### ISSUE THREAD

**Issue by prolic** [amphp/amp#235]
Is it possible to have a swoole adapter just like the react adapter that you already have?

**Comment by kelunik** [comment]
I'm not sure, haven't looked too much into Swoole. My personal favorite is [`ext-async`](https://github.com/concurrent-php/ext-async) in favor of a userland event loop.

**Comment by prolic** [comment]
Much love for ext async. But didn't you say it's not stable enough for production usage?

**Comment by kelunik** [comment]
That's correct.

**Comment by codeliner** [comment]
Found this one: https://github.com/swoole/library/blob/master/src/Swoole/Driver/Amp.php

Looks like Swoole team is working on react and amp integration.

**Comment by prolic** [comment]
@kelunik As swoole provides the bridge, I think we can close this ticket?

**Comment by kelunik** [comment]
Yes, let's close this then.

**Comment by zek** [comment]
So what's the status of this issue?

The link is invalid :(

**Comment by enumag** [comment]
@zek Why asking here? Ask the Swoole authors where they moved it to.

**Comment by rela589n** [comment]
@codeliner , @zek, did you find out?

**Comment by xpader** [comment]
I don't swoole is a good choice, ev, uv, event is better.

**Comment by rela589n** [comment]
@xpader , among all the existing solutions, only swoole provides native PHP support, so this is the way to go right now. There's no solution whereon you can run for example symfony project with full async support but swoole. This is the only solution I'm aware of of that makes existing blocking php functions non-blocking. Thus, having swoole adapter is a good thing to consider

**Comment by xpader** [comment]
@rela589n If using swoole, there's no reason to use amphp, swoole have fully async network server/client, async file io, coroutine support, and it's all implement by extension, it's different way to amphp.

They are not dependent relationships, but mutually exclusive relationships.
