### ISSUE TITLE
How to correctly turn closure to promise?

### ISSUE THREAD

**Issue by rawaludin** [amphp/amp#238]
Hello guys, just started learning about amphp. Really excited!

I want to convert sync call to async call using event loop in amphp. My sample code use `file_get_contents` as sample blocking call. 

Using sync call, it look like this:

    $uris = [
        "https://google.com/",
        "https://github.com/",
        "https://stackoverflow.com/",
    ];
    
    $results = [];
    foreach ($uris as $uri) {
        var_dump("fetching $uri..");
        $results[$uri] = file_get_contents($uri);
        var_dump("done fetching $uri.");
    }
    
    foreach ($results as $uri => $result) {
        var_dump("uri : $uri");
        var_dump("result : " . strlen($result));
    }

And the output:

    string(30) "fetching https://google.com/.."
    string(34) "done fetching https://google.com/."
    string(30) "fetching https://github.com/.."
    string(34) "done fetching https://github.com/."
    string(37) "fetching https://stackoverflow.com/.."
    string(41) "done fetching https://stackoverflow.com/."
    string(25) "uri : https://google.com/"
    string(14) "result : 48092"
    string(25) "uri : https://github.com/"
    string(14) "result : 65749"
    string(32) "uri : https://stackoverflow.com/"
    string(15) "result : 260394"

I know there's artax that would do the call in async. But, I want to learn how to correctly turn blocking code into async concurrent code (not parallel). I'm already success implementing it in parallel using amp parallel-functions (yay!).

I believe the correct output if I successfully implement it in async in amp, will be something like this:

    string(30) "fetching https://google.com/.."
    string(30) "fetching https://github.com/.."
    string(37) "fetching https://stackoverflow.com/.."
    string(34) "done fetching https://google.com/."
    string(34) "done fetching https://github.com/."
    string(41) "done fetching https://stackoverflow.com/."
    string(25) "uri : https://google.com/"
    string(14) "result : 48124"
    string(25) "uri : https://github.com/"
    string(14) "result : 65749"
    string(32) "uri : https://stackoverflow.com/"
    string(15) "result : 260107"

I've tried with this code:

    <?php
    require __DIR__ . '/vendor/autoload.php';
    
    use Amp\Loop;
    use function Amp\call;
    
    Loop::run(function () {
        $uris = [
            "https://google.com/",
            "https://github.com/",
            "https://stackoverflow.com/",
        ];
    
        foreach ($uris as $uri) {
            $promises[$uri] = call(function () use ($uri) {
                var_dump("fetching $uri..");
                $result = file_get_contents($uri);
                var_dump("done fetching $uri.");
                yield $result;
            });
        }
    
        $responses = yield $promises;
    
        foreach ($responses as $uri => $result) {
            var_dump("uri : $uri");
            var_dump("result : " . strlen($result));
        }
    });

Instead giving me my expected result, it give me this error:

    string(30) "fetching https://google.com/.."
    string(34) "done fetching https://google.com/."
    string(30) "fetching https://github.com/.."
    string(34) "done fetching https://github.com/."
    string(37) "fetching https://stackoverflow.com/.."
    string(41) "done fetching https://stackoverflow.com/."
    PHP Fatal error:  Uncaught Amp\InvalidYieldError: Unexpected yield; Expected an instance of Amp\Promise or React\Promise\PromiseInterface or an array of such instances; string yielded at key 0 on line 20 

The result also seems run in sync, not async.

How should I correctly do it?

**Comment by staabm** [comment]
As long as you use blocking calls you wont get the result you expect (except you use the parallel-functions lib or similar parallelization primitives).

**Comment by rawaludin** [comment]
So I need to convert the blocking call to parallel code first? 

So my assumption that reactphp will turn blocking sync I/O into async concurrent (not parallel) is wrong then? 

Sorry, I just started this library. So many things not really obvious for me from the docs.

**Comment by rawaludin** [comment]
@staabm thanks for replying :) 

So I need to convert the blocking call to parallel code first?

So my assumption that amphp will turn blocking sync I/O into async concurrent (not parallel) is wrong then?

Sorry, I just started this library. So many things not really obvious for me from the docs.

**Comment by kelunik** [comment]
You need to switch to a non-blocking implementation like Artax, file_get_contents is blocking and that won't change.

**Comment by rawaludin** [comment]
Okay, so file_get_contents in my case is just an example of blocking call. Now I know that I have to build my own non-blocking function. 

Could you give me simple example of converting a blocking function into a non-blocking function? 

Sorry, if this too much to ask.

**Comment by kelunik** [comment]
Maybe rewriting your example with Artax helps?

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use Amp\Loop;
use function Amp\call;

Loop::run(function () {
    $uris = [
        "https://google.com/",
        "https://github.com/",
        "https://stackoverflow.com/",
    ];

    $httpClient = new Amp\Artax\DefaultClient;

    foreach ($uris as $uri) {
        $promises[$uri] = call(function () use ($uri, $httpClient) {
            var_dump("fetching $uri..");
            $response = yield $httpClient->request($uri);
            $result = yield $response->getBody();
            var_dump("done fetching $uri.");
            return $result;
        });
    }

    $responses = yield $promises;

    foreach ($responses as $uri => $result) {
        var_dump("uri : $uri");
        var_dump("result : " . strlen($result));
    }
});
```

Any blocking call you want to replace needs to be replaced with a promise-returning function that uses promise-returning functions for any blocking I/O call.

**Comment by choval** [comment]
@rawaludin I've uploaded an example of how I'm doing it.

https://github.com/choval/amphp-non-blocking-example

**Comment by rawaludin** [comment]
@choval Thanks!

I've question though. Is using DefaultWorkerFactory equal to using parallel or is it a concurrent one? My goal was to execute the code in concurrent. 

I've successfully implemented my sample in parallel with this code:

```
<?php
require __DIR__ . '/vendor/autoload.php';

use function Amp\ParallelFunctions\parallelMap;
use Amp\Promise;

$uris = [
  'https://google.com/',
  'https://github.com/',
  'https://stackoverflow.com/',
];

$values = Promise\wait(parallelMap($uris, function ($uri) {
    var_dump("fetching $uri..");
    $result = file_get_contents($uri);
    var_dump("done $uri.");

    return [
          'uri' => $uri,
          'result' => $result
      ];
}));

foreach ($values as $result) {
    var_dump("uri : " . $result['uri']);
    var_dump("result : " . strlen($result['result']));
}
```

**Comment by rawaludin** [comment]
@techno-express Thank you!
That is the answer I'm looking for :)

You know, I have code some golang code and tried to compare all this coroutine stuff on amphp with golang. I've come from understanding that parallelism is not concurrency https://blog.golang.org/concurrency-is-not-parallelism

And trying to get my head around the amp. I was thought that amp would do concurrency like golang.

**Comment by kelunik** [comment]
@techno-express Artax _does not_ use `amphp/parallel` to make concurrent HTTP requests. It uses asynchronous I/O and `stream_select` or whichever backend the event loop implementation in use uses. Amp is mainly focused on _concurrency_, but also allows true _parallel_ execution via `amphp/parallel`.

Maybe reading https://blog.kelunik.com/2017/11/06/magic-behind-async-php.html helps a bit.

As maintainers of this library we're so used to the concept that we're not very good at explaining it to total newcomers, so we're always happy about any questions you might have. If you later have a better understanding, it'd be great if you could contribute back what you learned in form of documentation PRs, so future newcomers can have a better start.

**Comment by rawaludin** [comment]
@kelunik Okay, I've read the blog. Here's what I've used to understand concurrency and goroutine in golang https://gobyexample.com/goroutines

```
// A _goroutine_ is a lightweight thread of execution.

package main

import "fmt"

func f(from string) {
    for i := 0; i < 3; i++ {
        fmt.Println(from, ":", i)
    }
}

func main() {

    // Suppose we have a function call `f(s)`. Here's how
    // we'd call that in the usual way, running it
    // synchronously.
    f("direct")

    // To invoke this function in a goroutine, use
    // `go f(s)`. This new goroutine will execute
    // concurrently with the calling one.
    go f("goroutine")

    // You can also start a goroutine for an anonymous
    // function call.
    go func(msg string) {
        fmt.Println(msg)
    }("going")

    // Our two function calls are running asynchronously in
    // separate goroutines now, so execution falls through
    // to here. This `Scanln` requires we press a key
    // before the program exits.
    fmt.Scanln()
    fmt.Println("done")
}
```

Output:

```
$ go run goroutines.go
direct : 0
direct : 1
direct : 2
goroutine : 0
going
goroutine : 1
goroutine : 2
<enter>
done
```

Is it possible to convert that code to amphp version?
