### ISSUE TITLE
is it possible to get variable from loop

### ISSUE THREAD

**Issue by adeptofvoltron** [amphp/amp#241]
Inside my class I got method with something like that:
``` 
Loop::run(function () use ($request){
            try {
                $this->logger->info('Soap async xml request', ['request' => $request->asXML()]);
                $client = new \Amp\Artax\DefaultClient;
                $requestBuilder = new \Amp\Artax\Request($this->wsdlUrl, 'POST');
                $requestBuilder->withBody($request->asXML());
                $requestBuilder->withHeaders(
                    [
                        'Accept' => 'text/xml',
                        'Content-type' => 'text/xml',
                        'apikey' => $this->wsApiKey,
                    ]
                );
                $promise = $client->request($requestBuilder);
                $response = yield $promise;
                $body = yield $response->getBody();
            } catch (\Exception $error) {
                throw new ArmoneyException($e);
            }
        });

```

what is the bestway to get access to value of $body variable outside the "run"" method? or maybe I am doing something wrong

**Comment by kelunik** [comment]
The easiest way would be to replace `Loop::run` with `Amp\Promise\wait` and returning `$body` just like in a normal function. However, that only works if you have an otherwise synchronous application and just want to mix in a minor portion of async code.

If you have a fully asynchronous application, `Loop::run()` gives up the control flow to the event loop and never returns until the application exists. In that case you'd put the code handling the `$body` inside `Loop::run()` instead of putting it afterwards.

**Comment by adeptofvoltron** [comment]
for me option nr.1 will work but ...
In that case I do not know how the "promise" for wait method should be created. shall I write my own class implementing \Amp\Promise?
or there is some other way?

**Comment by kelunik** [comment]
@adeptofvoltron You wrap the closure additionally in `Amp\call`, so it's `wait(call(function () { ... }));` then.

Side note: I just noticed that you're using `$requestBuilder->withBody()` without assigning the result to `$requestBuilder` again. `Request` instances are immutable and the mutation functions all return new instances, so you need to use `$request = $request->withBody(...);`.

**Comment by kelunik** [comment]
It seems like all questions have been answered. If not, please respond with further questions, the issue can always be re-opened. :+1:
