### ISSUE TITLE
$this->now not fresh in NativeDriver->activate()

### ISSUE THREAD

**Issue by tjernblom** [amphp/amp#243]
Thank you for a supreme framework!
I found an error in lib/Loop/NativeDriver.php which needs to be fixed.

The issue:
I'm running a loop with a socket server based on the example at https://amphp.org/getting-started/tcp-chat/broadcasting
When adding delayed functions, for instance as a response to a socket message, they are immediately executed. After some testing I found that `$this->now` is only refreshed at the end of `activate()` which does not run frequently here. This means all new `$this->timerExpires[$watcher->id]` get old values, which make them expire immediately.

The solution:
Either change line 268 in NativeDriver.php to `$this->now = ...`   and remove line 312. I would suggest this as it keeps `$this->now` as fresh as possible.
You could also change line 286 to `$expiration = $now + ...`

**Comment by Bilge** [comment]
I'm still getting symptoms of this problem on Amp v2.1.1, but only when my async code is launched via `\Amp\Promise\wait`. If I wrap the same code in an `\Amp\Loop::run` block, it executes in good time. By *good time*, I mean it waits _at least_ the amount of time specified by a `Delayed`, whereas with `wait()` it yields a few milliseconds too early.

**Comment by trowski** [comment]
@Bilge Post here so others know we discussed it in IRC and what the resolution was: What you're seeing is the fact that timer interval is calculated from the moment of timer creation, not after the call to `Loop::run()`. When you create a timer before calling `Promise\wait()`, a few extra milliseconds pass before `Loop::run()` is called. When wrapping within a `Loop::run()` defer callback, the timer is being created within an already running loop.
