### ISSUE TITLE
Consider using Ds instead of SPL collections

### ISSUE THREAD

**Issue by jakobmats** [amphp/amp#247]
SPL data structures have their problems, one of them being their overall performance. It would be better to use the obvious alternative, Ds. While it's not distributed with every PHP installation by default there is a polyfill available that can be required in composer.json to keep the code fully functional. Using it across all packages would be cool too.

Benchmarks: https://medium.com/@rtheunissen/efficient-data-structures-for-php-7-9dda7af674cd
Ds: http://php.net/manual/en/book.ds.php
Ds polyfill: https://github.com/php-ds/polyfill

**Comment by bwoebi** [comment]
I'm not strictly opposed to that, however, what's the actual performance benefit (for amp)? Is it worth it?

**Comment by staabm** [comment]
i think it will only make sense when the phpds polyfill is comparable in performance with the spl classes. Phpds as a extension will not be available on most installations I guess

**Comment by jakobmats** [comment]
> i think it will only make sense when the phpds polyfill is comparable in performance with the spl classes. Phpds as a extension will not be available on most installations I guess.

Unfortunately currently the polyfill is nowhere near the performance that can be reached with the native extension so the suggestion doesn't really make much sense at least for now.

**Comment by kelunik** [comment]
We have considered `ext-ds`, but the polyfill performance is worse than SPL. Generally, we haven't seen the used data structures being a visible performance bottleneck in benchmarks.
