### ISSUE TITLE
Loop::run not stopping with Loop::stop in Loop::delay

### ISSUE THREAD

**Issue by Mulkave** [amphp/amp#249]
The objective is run a sync task with a timeout, the way i found most relevant is similar to the second example of the event loop api docs: https://amphp.org/amp/event-loop/api

Here's what i've tried, but the loop waits till the 10s are done and then calls the function in `delay` and stops.

```php
Loop::run(function () use ($msg, &$result) {
    $watcherId = Loop::defer(function () use ($msg, &$result) {
        var_dump('started running');
        sleep(10);
    });

    // set the time to stop the loop
    Loop::delay(500, function() use ($watcherId) {
        var_dump('delayed called');
        Loop::cancel($watcherId);
        Loop::stop();
    });

    var_dump('end of loop');
});
```

The sequence of output is:

```
end of loop
started running
.... wait for 10s ....
delayed called
```

Expected output
```
end of loop
started running
... wait for 500ms ....
delayed called
```

What am i doing wrong?

**Comment by kelunik** [comment]
The event loop implements concurrency via cooperative multitasking. It only has a chance to execute the timer if the `sleep` call returns. Thus, it's generally not possible to abort blocking tasks after a given timeout. Instead of using `sleep(10)`, you can use `yield new Delayed(10000)` for a cooperative version of waiting.

**Comment by Mulkave** [comment]
Thanks @kelunik.

And if i were to run some synchronous code instead of the `sleep(10)` or `new Delayed`, how do you suggest to do that (given that the sync code does not `yield`, it's simply data processing that takes a while but shouldn't exceed the given timeout (delay).

**Comment by kelunik** [comment]
It's not possible, except if you move the blocking operation into another thread / process and kill that. There's no preemptive scheduling, only cooperative scheduling.

**Comment by Mulkave** [comment]
Sorry for my many questions, trying to figure out a way to work it out.

If the blocking operation were to return a promise instead? Something as such:

Assuming this is within a `callBlockingCode` method
```php
$deferred = new Deferred();

Loop::delay(0, function ($watcherId) use ($deferred) {
    // blocking code that could take a while
    
    $deferred->resolve(true);
});

return $deferred->promise();
```

I tried two approaches:

**Approach 1**

The execution happens within the loop.

```php
Loop::run(function () use ($msg) {
    Loop::delay(1000, function() {
        var_dump('delayed called');
        Loop::stop();
    });

    $promise = $this->callBlockingCode();
    $promise->onResolve(function (Throwable $exception, $result) {
       var_dump(['result' => $result]);
    });
});
```
This still doesn't stop the loop and halt the process, `Loop::delay` is not being called untill the promise is resolved.

**Approach 2**

Replace `Loop::run` and `Loop::delay` with `Promise\timeout` and `Promise\wait`.

```php
$promise = $this->callBlockingCode();
$promise = Promise\timeout($promise, 1000);
$promise->onResolve(function ($exception, $result) {
   var_dump(['result' => $result]);
});

Promise\wait($promise);
```

The code is still executing and finishing even though taking longer that 1s.

**Note: No longer using sleep, now running the actual code that does the processing**

**Comment by bwoebi** [comment]
A Loop::delay(0) is _not_ another thread or process. You'll need a real process (e.g. amphp/process or amphp/parallel).

**Comment by kelunik** [comment]
It seems like all questions have been answered. If not, please respond with further questions, the issue can always be re-opened. :+1:
