### ISSUE TITLE
100% CPU Usage using NativeDriver

### ISSUE THREAD

**Issue by prolic** [amphp/amp#251]
I realized I have 100% CPU usage using this library [amphp/http-server]. I initially thought I did something very stupid somewhere, so just to be sure I tried this example:
https://github.com/amphp/http-server/blob/master/examples/hello-world.php

100% CPU usage as well!

**Comment by prolic** [comment]
thanks for the quick fix!

**Comment by bwoebi** [comment]
@trowski @kelunik Is there any real way we can _test_ for accidental CPU usage skyrocketing?

**Comment by kelunik** [comment]
@bwoebi Even if we can, what do you want to do then?

**Comment by bwoebi** [comment]
@kelunik just for catching regressions; setting up a few fairly typical workloads and check whether CPU is idling or not.
