### ISSUE TITLE
support for 32 bit systems?

### ISSUE THREAD

**Issue by gharlan** [amphp/amp#252]
Do you want to support 32bit systems?

I tried to use artax on an older server, but it does not work.
The return value of [`getCurrentTime`](https://github.com/amphp/amp/blob/23b8bd2cfe2efeb7461640b355e8d856316323fe/lib/Internal/functions.php#L60) is too big for 32bit, so the return value is a negative int.

And in [this line](https://github.com/amphp/amp/blob/7075ef7d74dbd32626bfd31c976b23055c3ade6a/lib/Loop/NativeDriver.php#L51) an error is thrown, because argument 2 is smaller than argument 1.

**Comment by kelunik** [comment]
I guess you're using PHP 7.3?

**Comment by gharlan** [comment]
No, 7.2.

**Comment by kelunik** [comment]
Does everything work fine with versions < 2.1?

**Comment by mstrouhal** [comment]
@kelunik Yes, it does. Problem started to occur after update do 2.1 version.

**Comment by qq15870939565** [comment]
How did you deal with this problem, I also encountered

**Comment by mstrouhal** [comment]
The only solution I have found so far is to require older version of amp:
```
"amphp/amp": "2.0.7"
```

**Comment by qq15870939565** [comment]
I am getting an error when adding a database. The database I am using is  https://github.com/auraphp/Aura.SqlQuery

**Comment by trowski** [comment]
I pushed a commit to the [fix-252](https://github.com/amphp/amp/tree/fix-252) branch. Please try this on a 32-bit system and let me know if it fixes the problem.

**Comment by tunnela** [comment]
@trowski it fixes the problem :+1:

**Comment by kelunik** [comment]
@gharlan @tunnela @qq15870939565 Please test with the latest `master`.

**Comment by qq15870939565** [comment]
OK。
Thank you



发送自 Windows 10 版邮件应用

发件人: Niklas Keller
发送时间: 2019年6月1日 2:17
收件人: amphp/amp
抄送: qq15870939565; Mention
主题: Re: [amphp/amp] support for 32 bit systems? (#252)

@gharlan @tunnela @qq15870939565 Please test with the latest master.

**Comment by kelunik** [comment]
Released a bugfix version, please report if there are further issues.
