### ISSUE TITLE
Migration guide from another async library

### ISSUE THREAD

**Issue by muglug** [amphp/amp#255]
Supposing I wanted to migrate [a project](https://github.com/vimeo/psalm) that was using `sabre/event` to use Amp, is there any guide that would provide some sort of mapping between concepts?

Specifically looking for equivalents to
  - [`Sabre\Event\Emitter::on`](https://github.com/sabre-io/event/blob/09c9c03c9b8f6917257cf4bed40b0dc49743ded9/lib/EmitterTrait.php#L22-L38)
  - [`Sabre\Event\Loop::addReadStream`, `addWriteStream`, `removeReadStream`, `removeWriteStream`](https://github.com/sabre-io/event/blob/09c9c03c9b8f6917257cf4bed40b0dc49743ded9/lib/Loop/Loop.php#L102-L160)

**Comment by muglug** [comment]
Still don't really know what I'm doing, but here's my WIP: https://github.com/vimeo/psalm/compare/amphp-wip

**Comment by trowski** [comment]
@muglug I'll take a close look at your branch this weekend and see if I can help out a bit. 😃

**Comment by muglug** [comment]
PR is here: https://github.com/vimeo/psalm/pull/1212

Everything passes and seems to work, so I'll probably merge tomorrow or Sunday.
