### ISSUE TITLE
PHP Warning produced when phpdbg is used

### ISSUE THREAD

**Issue by ostrolucky** [amphp/amp#258]
`PHP Warning:  pcntl_signal_dispatch() has been disabled for security reasons in vendor/amphp/amp/lib/Loop/NativeDriver.php on line 155`

**Comment by trowski** [comment]
I suppose we could use `ini_get('disabled_functions')` and search the array for `pcntl_signal_dispatch`, disabling single handling if the function is in the array… but that's not the *only* function required for signal handling – or loop operation in general – so I'm not sure if this is something we should handle.

**Comment by ostrolucky** [comment]
Yeah I don't see into this much so not sure how feasible it is. Feel free to close if you determine it's not possible to have amphp running with phpdbg

**Comment by trowski** [comment]
phpdbg doesn't disable that function by default, so it must be defined in the ini.

phpdbg can run Amp, in fact we often use it for our tests. However, from what I understand signal handling does not work with phpdbg, which may be why that function was disabled (since it won't work anyway).
