### ISSUE TITLE
Add PromisePool

### ISSUE THREAD

**Issue by prolic** [amphp/amp#259]
I ran into situations, where I handle lots of promises and when they are not resolved quick enough, the server runs out of memory. My idea is to add a kind of `PromisePool` similar to what we have as `ConnectionPool` within `Amp\Sql`.

Thoughts?

**Comment by prolic** [comment]
One problem I see: If you try to add a huge amount of callbacks to your pool, you might also get a memory limit problem, however usually you should reach that way slower, compared to not having any pool at all.

**Comment by Ejz** [comment]
```
while ($value = yield \Amp\Promise\any($promisePool)) {
    doSomething();
}
```
