### ISSUE TITLE
Non-cooperative coroutine

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#261]
When using coroutines which do not work on streams / sockets, or proactively deferring themselves via `yield new Delayed()` or sth, then a coroutine may block the loop even though it looks like wonderful async code.

The reason is that the coroutine is looping over the generator without ever returning the control to the loop. Of course, this can be handled by application code but this is:
- hard to maintain
- debug
- not cooperative

Are you aware of this? Have you ever discussed this?

**Comment by kelunik** [comment]
Yes, we're aware of it. Longer computing operations should be moved to a worker pool using amphp/parallel, so they don't block the main loop. That way the kernel takes care of scheduling.

**Comment by trowski** [comment]
@brstgt I'm curious – could you be more specific on what you were doing? If there's room for improvement I'm always interested in hearing suggestions.

**Comment by brstgt** [comment]
We wrote some code using coroutines + promises but it is not really async in a way that it does network requests or passes controll back to the loop in a way.
At the same time we need to run other code in intervals. This code never ran as the "main task" never passed back control to the loop even though it was basically layed out to run in coroutines that could be interrupted. But without FD operations or timers coroutines run in "1 chunk", they are never interrupted and never pass control to the loop.

Was that clear?

**Comment by kelunik** [comment]
This is generally only a problem with either blocking functions or tight loops where I/O operations are always immediately possible. I think this is best handled in I/O abstractions to avoid immediate returns once in a while on many direct reads.
