### ISSUE TITLE
Possible adaptation of NativeDriver needed for sapi_windows_set_ctrl_handler in PHP 7.4

### ISSUE THREAD

**Issue by ostrolucky** [amphp/amp#262]
Hello, I welcome you to chip in to https://bugs.php.net/bug.php?id=77377 as this is something which can affect amp core. Current PHP master using sapi_windows_set_ctrl_handler and streams blocks for indifinite time. Reproduction is as simple as 
```php
sapi_windows_set_ctrl_handler(function() {
    exit(0);
});

$server = \Amp\Socket\listen('localhost:1337');
\Amp\Promise\wait($server->accept());
```

**Comment by kelunik** [comment]
Using a maximum timeout of one second sounds reasonable to me on Windows then. @bwoebi @trowski What do you think?

**Comment by kelunik** [comment]
@ostrolucky Seems like the following will actually be enough, no? That way, anyone can choose their minimum check frequency.

```php
// Avoid too long blocking if idle to make sapi_windows_set_ctrl_handler work
Loop::unreference(Loop::repeat(1000, function () {}));
```

**Comment by kelunik** [comment]
I'm moving this to https://github.com/revoltphp/event-loop/issues/29, as Revolt is the event loop used in Amp v3.
