### ISSUE TITLE
Stop suppressing stream_select errors

### ISSUE THREAD

**Issue by ostrolucky** [amphp/amp#265]
I spent some hours today debugging why do my loops hang. There are numerous occasions when `stream_select` does not work. Instead of throwing the error, loop is going forever, because for some unknown reason, [you throw only for one single type of error](https://github.com/amphp/amp/blob/272f78dcb2897bead923fd5f94c9b88b18e40f70/lib/Loop/NativeDriver.php#L179). 

Example 1:

```php
Loop::run(function() {
    $stream = fopen('php://memory', 'rwb');

    Loop::onWritable($stream, function() {
        throw new \Exception('I should have been thrown');
    });

    fwrite($stream, 'wat');
});
```

Example 2:

```php
Loop::run(function() {
    $stream = tmpfile();
    stream_filter_append($stream, "string.rot13", STREAM_FILTER_WRITE);

    Loop::onWritable($stream, function() {
        throw new \Exception('I should have been thrown');
    });

    fwrite($stream, 'wat');
});
```

Hereby I request you to stop ignoring stream_select errors as it leads to hard to debug issues.

**Comment by trowski** [comment]
I'm not entirely sure why only a single type of error is being thrown if `stream_select()` returned `false`. @kelunik Do you remember why this was done?

@ostrolucky Note that the streams you are passing to the loop in the examples above cannot be used with the event loop. Only socket can be polled. Memory streams and file streams will never invoke the watcher, thus the exceptions in your watchers can never be thrown. The error suppression was stopping you from seeing the error from `stream_select()` that the streams were invalid, not catching any exceptions.

**Comment by ostrolucky** [comment]
Yes I know now, see
> There are numerous occasions when stream_select does not work

I'm not blaming you, that's stream_select limitation. But I didn't that when I was trying it. I would realize that much sooner if error wasn't silenced :)

**Comment by trowski** [comment]
I guess `'I should have been thrown'` as the exception message made me think you were expecting that to be thrown but your complaint was that it was not. We're on the same page now, no worries.

**Comment by ostrolucky** [comment]
Actually rereading your comment, this is not entirely true

> Memory streams and file streams will never invoke the watcher

Second example will work when removing stream_filter_append. That's what's causing stream_select to not work. File resources are ok.

**Comment by trowski** [comment]
File resources appear to work, but will always report as readable or writable. So no, they don't actually work.

**Comment by ostrolucky** [comment]
Yep, except those with stream_filter :)

**Comment by ostrolucky** [comment]
@kelunik we are waiting for your input here

**Comment by kelunik** [comment]
See #160. It was the initial attempt to unignore errors which we don't want to suppress. 

https://github.com/amphp/amp/commit/a2477575355d1871779974c9e5902b70955071fb

We need to inspect which warnings we want to suppress and which we want exceptions for.

**Comment by ostrolucky** [comment]
I suggest to whitelist errors rather than blacklist. Blacklists are never complete.
