### ISSUE TITLE
Support the parallel extension

### ISSUE THREAD

**Issue by theofidry** [amphp/amp#266]
Would it make sense to add support for [`krakjoe/parallel`](https://github.com/krakjoe/parallel)?

**Comment by kelunik** [comment]
We already have a branch for that in `amphp/parallel`: https://github.com/amphp/parallel/tree/ext-parallel

**Comment by theofidry** [comment]
Brilliant, thanks

**Comment by theofidry** [comment]
@kelunik looking at it again, it doesn't look like there is a ParallelDriver is there?

**Comment by kelunik** [comment]
What kind of parallel driver are you looking for? There's https://github.com/amphp/parallel/blob/master/lib/Worker/DefaultWorkerFactory.php#L48

**Comment by theofidry** [comment]
Ah I see the drivers are for the event loop and parallel is for workers, my bad.

I'm looking for ways to optimize performances for HumbugBox, do you have any recommendations for the driver&worker? I tried with the `ev` extension but it appeared to be slower than with the NativeDriver...

**Comment by kelunik** [comment]
There's not much difference between the drivers except that many, many open streams will be slower with the native driver.
