### ISSUE TITLE
Real emitter example

### ISSUE THREAD

**Issue by enumag** [amphp/amp#270]
I'm looking into the docs and examples but I still can't understand how to write a function that:

- returns `\Amp\Iterator`
- can't emit all values in a single coroutine (= can't use `Producer` instead of `Emitter`)
- needs to make for example an async database call in the middle of emitting the values and use the result to emit more

Can I ask for an example like that? Everything I found so far seems way too simplified so it's not clear how to do this.

**Comment by Ejz** [comment]
```
#!/usr/bin/env php
<?php
require __DIR__ . '/../../vendor/autoload.php';
use Amp\Delayed;
use Amp\Emitter;
use Amp\Loop;
Loop::run(function () {
    try {
        $emitter = new Emitter;
        Loop::defer(function () use ($emitter) {
            // Listener emits all values at once.
            $emitter->emit(1);
            $emitter->emit(2);
            $emitter->emit(3);
            $emitter->emit(4);
            $emitter->emit(5);
            $emitter->emit(6);
            $emitter->emit(7);
            $emitter->emit(8);
            $emitter->emit(9);
            $emitter->emit(10);
            $emitter->complete();
        });
        $iterator = $emitter->iterate();
        while (yield $iterator->advance()) {
            \printf("Emitter emitted %d\n", $iterator->getCurrent());
            yield new Delayed(100); // Listener consumption takes 100 ms.
        }
    } catch (\Throwable $exception) {
        \printf("Exception: %s\n", $exception);
    }
});
```

**Comment by kelunik** [comment]
@enumag You can see such an example in https://github.com/amphp/redis/blob/494a32c2ec6d0eae9513cf955208a10e8f8682bd/src/Subscriber.php

**Comment by enumag** [comment]
@kelunik Thanks. I'll try to study this code then. Though I can tell already that it's by no means easy to understand and could use some comments.
