### ISSUE TITLE
Artax - How can we set proxies in http client

### ISSUE THREAD

**Issue by waleedmazhar** [amphp/amp#277]
Hi there,

How can we apply proxies in http client, in curl we use CURLOPT_PROXY and CURLOPT_HTTPPROXYTUNNEL

Is there a way we can set proxies in Artax http client?

thanks

**Comment by kelunik** [comment]
Yes, there is, see https://github.com/amphp/artax/blob/fb8c11fe7530be274483adf63346cc1b0fa1714a/lib/HttpSocketPool.php

Please open further issues regarding Artax in its own repository.
