### ISSUE TITLE
Return type

### ISSUE THREAD

**Issue by szepeviktor** [amphp/amp#279]
Hello!

What does this return type mean? `* @return \Amp\Promise<bool>`
Found in Iterator.

Could not find in these standards.
- https://docs.phpdoc.org/references/phpdoc/types.html
- https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md

**Comment by danog** [comment]
Simply means that a promise is returned that eventually resolves to a boolean, you should take a look at the amphp docs for promises

**Comment by szepeviktor** [comment]
Thank you.
