### ISSUE TITLE
 I am a novice, I do not know how to code but I'm having a big problem with AMP

### ISSUE THREAD

**Issue by aureliacphoto** [amphp/amp#284]
I first thank those who will take the time to read me despite the fact that I have neither the right vocabulary, nor your knowledge and experience.
 
That's exactly why today I turn to the github community because I'm helpless.

That's my problem is this. I'm a photographer, I have a website that is my only showcase to live my profession and I realized that "I went" (I put quotes because I did not ask for anything) AMP version as a result of search on Google.

This is a disaster for me since these pages are awful and for the content nothing is in its place. everything is bad. I have the pages of my blog on my homepage for example. This is completely harmful to my activity because I sell the image, photos!

The appearance of my site is crucial. I noticed since the establishment of the MPA a terrifying rebound rate and especially I do not receive any more mails of prospection. I am losing potential customers. This is a real disaster for my small business.

I would like to know if it is possible to remove these awful pages and return to my pages that I put so much time to create and think from an aesthetic point of view?

If only someone can help me.

Thank you very much for reading me.

Best regards

Aurélia

**Comment by trowski** [comment]
I believe you have confused our project with this project: https://github.com/ampproject.

Please open your issue in the appropriate repo there.
