### ISSUE TITLE
Async FTP client

### ISSUE THREAD

**Issue by enumag** [amphp/amp#287]
In my application there is some code that works with FTP using `ftp_get`. This is however blocking so I need to rewrite it to some non-blocking API. There is `ftp_nb_get` which I can use of course.

The catch is that there doesn't seem to be any non-blocking alternative for `ftp_rawlist` which I'm also using.

Do you guys know of any non-blocking FTP client which I could use either directly or for inspiration? Doesn't necessarily need to be based on Amphp.

Since I was unable to find anything myself I'll assume that no such client exists for now. What else should I do then in order to avoid using the blocking API?

**Comment by kelunik** [comment]
I'm not aware of any non blocking solution. I'd recommend to move the blocking code into a worker using amphp/parallel. You probably don't have very high load via FTP, but rather want to use it, but without blocking?

**Comment by enumag** [comment]
Yeah, exactly. Worker is something I was considering but wasn't sure if it was the recommended way. Looks like I was right. Thanks!
