### ISSUE TITLE
How to debug segfaults in libuv?

### ISSUE THREAD

**Issue by prolic** [amphp/amp#292]
When running the test suite of [event-store-client](https://github.com/prooph/event-store-client/)

I'm always getting this segfault, but not always on the same test case and if the test case is tested seperately it's green. So I cannot reproduce a single failing test, but only that the test suite itself somehow fails to pass the tests.

```
php: src/unix/core.c:925: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
[1]    8509 abort (core dumped)  ./vendor/bin/phpunit --exclude=ignore --testdox
./vendor/bin/phpunit --exclude=ignore --testdox  8,90s user 1,21s system 23% cpu 42,284 total
```

Given what I could find about this on google, libuv source code (f.e. https://github.com/libuv/libuv/issues/2387), I have no idea where this can come from. For each test case I create a new event store connection via TCP protocol using `\Amp\Socket\connect`. As logger (another source where something could read / write) a NullLogger is used during the tests.

Do you have any idea where I can look at?

System: Ubuntu 19.10
PHP: 7.3.11
uv: libuv1/eoan,now 1.30.1-1 amd64 [installed,automatic] (via Ubuntu's apt)

see also https://github.com/prooph/event-store-client/issues/75

**Comment by prolic** [comment]
ping @kelunik

**Comment by kelunik** [comment]
@prolic Please open an issue in the appropriate extension repository, so in https://github.com/bwoebi/php-uv. There are several articles on the web that might help, such as https://derickrethans.nl/phps-segmentation-faults-gdbfu.html and http://www.phpinternalsbook.com/php7/memory_management/memory_debugging.html.
