### ISSUE TITLE
TimerQueue has stability problems since the 2.1.2 rewrite

### ISSUE THREAD

**Issue by Bilge** [amphp/amp#296]
I cannot upgrade from Amp 2.1.1 due to intermittent stability issues with 2.1.2 and above. The relevant change was a complete rewrite of `TimerQueue` in that (minor) version. To be clear, this is a somewhat rare bug that rears its head once every 100,000 operations or so (those operations do not need to occur on the same thread or in the same job, it's an independent probability). I've captured the output of a job where this has occurred for reference and posterity. This was run on PHP 7.3 but it seems to affect all PHP 7 versions.

[output.txt](https://github.com/amphp/amp/files/3962942/108.txt)

To be clear, this absolutely never happens on Amp 2.1.1. That version is completely 100% stable, which is why I cannot justify upgrading any further, as stability is paramount.

**Comment by Bilge** [comment]
Somehow this is fixed by upgrading to PHP 7.4.

**Comment by Bilge** [comment]
This still affects PHP 7.4.2 on Windows.

```
In TimerQueue.php line 119:

  [ErrorException]
  Notice: Undefined offset: 125
```

Maybe it also affects Unix, but I just haven't run a program for long enough. It manifests itself on Windows after at least 1 hour running continuously at high Promise velocity.

**Comment by kelunik** [comment]
@Bilge Did the situation with 2.4.2 improve? I've switched from an anonymous class to a named class, just in case that makes a difference.

**Comment by Bilge** [comment]
@kelunik Thanks for the heads up. I'll test it. I've been back on 2.1.1 since February.

**Comment by Bilge** [comment]
PHP 7.4.2 Amp v2.4.4.

```
In TimerQueue.php line 119:

  Notice: Undefined offset: 377

```

**Comment by bwoebi** [comment]
Would it be possible for you to dump some information about the TimerQueue when this happens?

Like, adding to a set_error_handler: `if (strpos($errfile, "TimerQueue.php") !== false) $GLOBALS["dump_timer_info"] = true;`

And then, at the end of removeAndRebuild() in TimerQueue.php, add:
```
if (!empty($GLOBALS["dump_timer_info"])) {
  unset($GLOBALS["dump_timer_info"]);
  $out = "Data length: " . count($this->data) . " - operating length: $length - old id: $id - node: $node - swap: $swap - child: $child";
  $out .= "\n\nWatchers:";
  foreach ($this->data as $idx => $w) {
    $out .= "\n$idx => {$w->id}";
  }
  $out .= "\n\nPointers:";
  foreach ($this->pointers as $id => $idx) {
    $out .= "\n$id => $idx";
  }
  file_put_contents("php://stderr", $out); // or whatever you can easiest grab it from
}
```

**Comment by Bilge** [comment]
The problem is the _when this happens_ part. It's rare, even for me. I also don't know how `set_error_handler` is supposed to work. Besides never using it, it might conflict with Symfony in some way. What guarantees the code I add to `TimerQueue` even runs? It seems to be Symfony Console aborts as soon as the notice is emitted.

**Comment by bwoebi** [comment]
I guess you have some logic somewhere converting the notice to an exception then.
If you are using symfony, it's probably: https://github.com/symfony/error-handler/blob/master/ErrorHandler.php#L489 which is throwing. Just don't throw in the case this is true.
```
if (strpos($errfile, "TimerQueue.php") !== false) {
    $GLOBALS["dump_timer_info"] = true;
} elseif ($throw) {
...
```

**Comment by kelunik** [comment]
v2.5.0 fixes a bug in `TimerQueue`, please retry. :-)

**Comment by Bilge** [comment]
@kelunik Well, if nothing else, it finally fixed a long-standing issue with [timer precision guarantees being broken](https://travis-ci.org/github/ScriptFUSION/Retry/builds). See [this build](https://travis-ci.org/github/ScriptFUSION/Retry/jobs/708149936) passed only because Amp was upgraded. [First started failing 8 months ago when 2.4.0 was released](https://travis-ci.org/github/ScriptFUSION/Retry/jobs/610684734).

**Comment by kelunik** [comment]
I'm going to close this until it happens again. :-)
