### ISSUE TITLE
Nested loop example/question

### ISSUE THREAD

**Issue by tillkruss** [amphp/amp#304]
Hi! I'm looking for some advice, I hope this is the right place. I've never used AMP and couldn't find any examples for nested loops.

1. I'd like to paginate over an API endpoint until no more records are returned using blocking requests (not asynchronous).
2. Each iteration (API response) returns 50 records and I want to asynchronously perform an action for each record

```
- Fetch API: 0-50
- Spawn 50 asynchronous tasks
- Fetch API: 50-100
- Spawn 50 asynchronous tasks
- Fetch API: 100-150
- Spawn 50 asynchronous tasks
```

If any synchronous or asynchronous requests fails, the execution should continue but the error is logged.

**Comment by kelunik** [comment]
What's the reason for keeping the paginated requests as blocking?

**Comment by tillkruss** [comment]
@kelunik: They could be simultaneously as well, but I'd need to add a minor delay (50ms) between each request to avoid hitting API limits.

**Comment by kelunik** [comment]
I've added two examples to `amphp/http-client` that illustrate how it could look like. I hope that helps.

**Comment by tillkruss** [comment]
@kelunik: Fantastic, thank you!
