### ISSUE TITLE
Php conflicts rule

### ISSUE THREAD

**Issue by staabm** [amphp/amp#318]
Should amp define a composer conflicts rule to disallow to run it with php 7.4.6?

Is amp affected?

https://twitter.com/nikita_ppv/status/1264857231167807489?s=20

**Comment by kelunik** [comment]
We usually don't yield from plain arrays and generally don't use yield from across method boundaries, but rather use Amp\call instead, so it seems unnecessary.

Additionally, something like that might result in problems if distributions backport the fix.

**Comment by staabm** [comment]
I see, just figured its something to discuess. thanks for your opinion.
