### ISSUE TITLE
Iterators blocking other events

### ISSUE THREAD

**Issue by SeriousKen** [amphp/amp#320]
Maybe I'm misunderstanding something, but I'm finding that iterating over an iterator blocks other events. The following code doesn't seem to hit the repeat event during looping over the iterator.

```
Loop::run(function () {
    $timer = Loop::repeat(10, function () {
        echo '.';
    });
    Loop::unreference($timer);

    $iterator = new Producer(function ($emit) {
        for ($i = 0; $i < 1000000; $i++) {
            yield $emit($i);
        }
    });
    $items = [];

    echo "Starting loop.\n";
    while (yield $iterator->advance()) {
        $items[] = $iterator->getCurrent();
    }

    echo count($items)." items iterated.\n";
    echo "Loop complete.\n";
});
```

I would expect that yielding the advance method would allow the timer to advance and output a dot to the console, but it doesn't.

**Comment by kelunik** [comment]
It doesn't happen, because your emits always happen immediately. Try adding something like yield delay(1); to your producer.

**Comment by SeriousKen** [comment]
Thanks for that @kelunik. I'm still trying to get my head around exactly what is happening.

**Comment by enumag** [comment]
> I'm still trying to get my head around exactly what is happening.

What's happening I think is that the loop never has a chance to do the next tick.
