### ISSUE TITLE
issues with PHP preloader

### ISSUE THREAD

**Issue by danijelk** [amphp/amp#321]
We're trying to preload our laravel application using [Brents](https://stitcher.io/blog/preloading-in-php-74) example but are hitting an issue with amphp

`Fatal error: Cannot redeclare Amp\Process\escapeArguments() (previously declared in /app/vendor/amphp/process/lib/functions.php:30) in /app/vendor/amphp/process/lib/functions.php on line 30`

Weird thing is that amphp isn't in the preload, but as a solution would it make sense to surround helper functions provided by amphp with `( ! function_exists('...'))` like many other packages do?

**Comment by kelunik** [comment]
I think fixing all libraries to include such a check is the wrong way of fixing it. If the preloading requires a file that's then again required by Composer, then that's where things go wrong. IMO support should be added in Composer to check whether `"autoload": { "files": [...] }` files are already preloaded and skip them in this case.

**Comment by danijelk** [comment]
I'm not sure who is requesting it when tbh. The preloading works, as it just loads the framework classes. We use [rubix/ml](https://github.com/RubixML/RubixML) in our app which requires amphp. And hitting any route in our app, once everything is loaded, throws the fatal error, so the way down the rabbit hole is quite interesting. 

Will give it a dive next week to see what methods are actually going into amphp in a preload manner, as it might be that many many more packages have the same outcome, or if it's only amphp which I doubt.

**Comment by danijelk** [comment]
After some testing I can conclude that surrounding with `( ! function_exists('...'))` doesn't have any effect, and not preloading anything still yields this error. Amphp is the only package in our +50 composer.json that gives error sadly. I've asked for Brent's input to see if he has any pointers as I believe that he's one of few with the experience that could point in the right direction.

**Comment by enumag** [comment]
@danijelk Try adding `debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS)` to the top of the conflicting file. That way you will see where it is loaded from and should be able to judge which of the two cases should not be happening. That should put you on the right track to fix the issue.

**Comment by danijelk** [comment]
@enumag thanks for hint. I ended up figuring some details out, [this](https://github.com/DarkGhostHunter/Laraload) project explains the issue quite well. 

> Using require_once will execute all files, resolving all the links (parent classes, traits, interfaces, etc.) before compiling it, and may output heavy errors on files that shouldn't be executed. Depending on your application, you may want to use one over the other.

Since the preload.php example uses `require_once __DIR__ . '/vendor/autoload.php';` logically it will preload all helper functions, traits etc etc before it even scans our ->paths().
With this it makes sense that a second autoloader call will give us the error. Just for the record, even if we use require_once() it still fails, I guess it doesn't know it's preloaded and tries to require it again.

So with `debug_backtrace()` I could see what was calling the amphp ... functions.php

**Preload**
```
Array
(
    [0] => Array
        (
            [file] => /app/vendor/composer/autoload_real.php
            [line] => 69
            [function] => require
        )

    [1] => Array
        (
            [file] => /app/vendor/composer/autoload_real.php
            [line] => 59
            [function] => composerRequirebebea9ec969fefbfb154e44968b8fac9
            [args] => Array
                (
                    [0] => 8dc56fe697ca93c4b40d876df1c94584
                    [1] => /app/vendor/composer/../amphp/process/lib/functions.php
                )

        )

    [2] => Array
        (
            [file] => /app/vendor/autoload.php
            [line] => 7
            [function] => getLoader
            [class] => ComposerAutoloaderInitbebea9ec969fefbfb154e44968b8fac9
            [type] => ::
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /app/preload.php
            [line] => 3
            [args] => Array
                (
                    [0] => /app/vendor/autoload.php
                )

            [function] => require_once
        )

)
```

**Regular request**
```

Array
(
    [0] => Array
        (
            [file] => /app/vendor/composer/autoload_real.php
            [line] => 69
            [function] => require
        )

    [1] => Array
        (
            [file] => /app/vendor/composer/autoload_real.php
            [line] => 59
            [function] => composerRequirebebea9ec969fefbfb154e44968b8fac9
            [args] => Array
                (
                    [0] => 8dc56fe697ca93c4b40d876df1c94584
                    [1] => /app/vendor/composer/../amphp/process/lib/functions.php
                )

        )

    [2] => Array
        (
            [file] => /app/vendor/autoload.php
            [line] => 7
            [function] => getLoader
            [class] => ComposerAutoloaderInitbebea9ec969fefbfb154e44968b8fac9
            [type] => ::
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /app/public/index.php
            [line] => 24
            [args] => Array
                (
                    [0] => /app/vendor/autoload.php
                )

            [function] => require
        )

    [4] => Array
        (
            [file] => /Users/r/.composer/vendor/laravel/valet/server.php
            [line] => 191
            [args] => Array
                (
                    [0] => /app/public/index.php
                )

            [function] => require
        )

)

```


So with the help of Laraload's idea I simply removed the require_once of the autoloader, and switch from require_once to opcache_compile_file, and with come notices everything works and I see opcache stats have preloaded the things I needed.

Having that said, <del>this is still a mystery to me, I can't figure out why amphp is the only package that has this issue. There are +50 helper functions that are preloaded the same way, but none of them crash like this.</del>

Just as I was about to hit submit I tried some things, and found that if I remove the if(IS_WINDOWS) statement, everything works fine... I'll check with @nikic to see if this is a known issue or behaviour.

**Comment by kelunik** [comment]
@danijelk It's indeed conditionally defined. Do you know whether there's a way to do `if (is_preload()) { return; }` there, so it's simply not preloaded?

**Comment by danijelk** [comment]
> @danijelk It's indeed conditionally defined. Do you know whether there's a way to do `if (is_preload()) { return; }` there, so it's simply not preloaded?

I see your idea, but I believe forcing this logic to every package is bad practise, just like you mentioned in your first comment. Either opcache preloader sees the condition and therefor doesn't preload it, which means amphp should move logic out of autoloaded helper, or this is a bug in the preload logic and can be fixed there.

Would be great with a composer->autoload->without_helpers :)

**Comment by kelunik** [comment]
@danijelk Did you report this upstream somewhere?

**Comment by danijelk** [comment]
@kelunik Didn't get a reply at that point when trying though github and twitter, will try to add to php issue list once back from vacation to push for an answer.

**Comment by danijelk** [comment]
I can't really replicate it in an empty project so I'll close it for now, must be something in the laravel/composer combo that loads it one too many times.

**Comment by ctrl-f5** [comment]
just to add to the conversation, since I've been struggling with this for hours and this was the only thing issue was the only thing I could find on it. I'm also having this issue with symfony 5.1.

All autoloaded files that have functions declared conditionally will produce this issue.

**Comment by kelunik** [comment]
Please open an upstream issue in symfony then.

**Comment by ctrl-f5** [comment]
it's not a symfony, laravel or composer issue, the problem is with this file: https://github.com/amphp/process/blob/master/lib/functions.php

When included it causes a duplicate definition in combination with opcache preload. [Even though the docs state](https://www.php.net/manual/en/opcache.preloading.php):

> include will execute code in the file, while opcache_compile_file() will not. That means only the former supports conditional declaration (functions declared inside an if-block).

I'll have a look at reporting an issue with php itself and see where that leads.
