### ISSUE TITLE
Doing async job while sending http request

### ISSUE THREAD

**Issue by proArtex** [amphp/amp#323]
Hi there! I am trying to understand whether it is possible to do some async job while sending async http request in the same Loop of the same php process.

My goal is to iterate over a long array and filter it by "evaluating" each item (time & cpu consuming op). Filtered items contain a url that should be requested. But to avoid awaiting for response I could continue iterating meanwhile. I've tried using producer/consumer pattern but "yield $client->request()" blocks everything. Is there a way of handling such task?

**Comment by Pato05** [comment]
afaik, you can remove yield or store the promise in a variable ready to be yielded to get its response

**Comment by proArtex** [comment]
Hey @Pato05, thanks for the quick response. Do you have any references so that I could dig deeper?

**Comment by Pato05** [comment]
> Hey @Pato05, thanks for the quick response. Do you have any references so that I could dig deeper?

No worries. Yes, I do: https://amphp.org/amp/coroutines/. If yield gets the Coroutine to subscribe to the promise, I think removing it prevents this, and let the other code continue. But this works only if what you're yielding is a coroutine, if it is a generator i think you can use `new Coroutine(...);`

**Comment by kelunik** [comment]
@proArtex Do you want to completely decouple the filtering and requesting of the URLs or just be a bit ahead with the filtering? Do you want concurrent requests or only one at a time?

**Comment by proArtex** [comment]
@kelunik I was planing to send requests one by one in synchronous manner and be at least a bit ahead with filtering to find the next appropriate item by the time I got response. Kind of spending io time smart. So it would basically look like this:

```
EVALUATION QUEUE     |  HTTP REQUESTS QUEUE
...                  |  awaiting
filter neg (ignore)  |  awaiting
filter pos           |  request #1 (few ticks)
filter neg (ignore)  |  request #1 (few ticks)
...                  |  request #1 (completed)
...                  |  request #2 (few ticks)

```

**Comment by trowski** [comment]
Using `yield` within a coroutine pauses execution the coroutine until the promise resolves. It also allows other coroutines to resume execution if the promise that was yielded has resolved. To concurrently process data and separately await promises, you'll need to create a separate coroutine to process the data from each response.

```php
$promises = [];
foreach ($uris as $uri)
    $response = yield $httpClient->request(new Request($uri));

    $promise = Amp\call(function () use ($response, $uri) { /* Process data */ });
    $promise[$uri] = $promise;
    $promise->onResolve(function () use ($uri) { unset($promises[$uri]); });
}

Amp\Promise\all($promises); // Wait for remaining data processing to finish.
```

This is a very simplified approach. Likely you'd have a consumer object doing the data processing. That object could keep a list of pending jobs instead of the array of promises in the above example.

**Comment by proArtex** [comment]
@trowski thank you for clarifying this! As far as I understand 2 coroutines would solve the issue, since I need to iterate synchronously in both of them. Here is a piece of code that I believe should work, it works correct in the very beginning (as to output) but then it is awaiting response to switch to another coroutine. What am I doing wrong?

```
$client = HttpClientBuilder::buildDefault();
$records = [];
for ($i = 0; $i < 11; $i++) {
    $records[] = $i;
}


Loop::run(
    function () use ($client, $records) {
        $emitter = new Emitter;

        Loop::defer(function () use ($emitter, $records) {
            Amp\call(
                function () use ($emitter, $records) {
                    $record = current($records);
                    do {
                        echo 'evaluate ' . $record . PHP_EOL;

                        // complex evaluation goes here
                        if ($record % 2 === 0) {
                            yield $emitter->emit($record);
                        }

                    } while ($record = next($records));

                    $emitter->complete();
                }
            );
        });

        $iterator = $emitter->iterate();

        Amp\call(function () use ($client, $iterator) {
            while (yield $iterator->advance()) {
                echo 'request ' . $iterator->getCurrent() . PHP_EOL;
                $record = $iterator->getCurrent();
                $response = yield $client->request(new Request("http://127.0.0.1:9999?r={$record}", 'GET'));
                yield $response->getBody()->buffer();
                echo 'response ' . $iterator->getCurrent() . PHP_EOL;
            }
        });
    }
);

echo 'DONE'. PHP_EOL;
```

The output:
```
evaluate 0
request 0
evaluate 1
evaluate 2
response 0
evaluate 3
evaluate 4
request 2
response 2
evaluate 5
evaluate 6
request 4
response 4
evaluate 7
evaluate 8
request 6
response 6
evaluate 9
evaluate 10
request 8
response 8
request 10
response 10
DONE
```

**Comment by proArtex** [comment]
I ended up replacing this
```
// complex evaluation goes here
 if ($record % 2 === 0) {
    yield $emitter->emit($record);
}
```

with this
```
// complex evaluation goes here
if ($record % 2 === 0) {
    $emitter->emit($record);
}

yield new \Amp\Delayed(0);
```

It seems to be working.

**Comment by kelunik** [comment]
Why do you use current and next instead of foreach?

**Comment by proArtex** [comment]
@kelunik it is a short version of my code, it could be indeed replaced with foreach. But I am using while() since in further implementation it has one more variable to stop the Emitter depending on the type of response http client gets.

**Comment by proArtex** [comment]
One thing I don't really like though: `yield new \Amp\Delayed(0)`. Is there a prettier way of yielding to another coroutine?

**Comment by kelunik** [comment]
It usually only makes sense to yield to other coroutines if there are IO tasks or timers to wait on. If you don't have that, but still want to yield, using yield delay(0) is the right thing to do.

What's unexpected in the output you posted above?

**Comment by proArtex** [comment]
Got it. Awaiting response starting with request 2 was unexpected for me since there was "yield" on the http request.
```
...
request 2
response 2
...
request 4
response 4
...
```
The replacement I mentioned above fixes the issue and the output becomes like this:
```
evaluate 0
request 0
evaluate 1
evaluate 2
evaluate 3
evaluate 4
response 0
request 2
evaluate 5
evaluate 6
evaluate 7
evaluate 8
response 2
request 4
evaluate 9
evaluate 10
response 4
request 6
response 6
request 8
response 8
request 10
response 10
DONE
```

**Comment by proArtex** [comment]
@kelunik @trowski We would like to use symfony http client (that uses amp http client underhood) instead of amp http client itself. Is this possible for my implementation? I've noticed they are using Loop::start() inside AmpResponse class.

**Comment by kelunik** [comment]
You won't be able to mix Amp and Symfony Http Client. If you plan to use other Amp libraries in combination, I'd strongly recommend using `amphp/http-client` directly.

**Comment by proArtex** [comment]
@kelunik got it, thank you.
