### ISSUE TITLE
Question: Does yield always wait?

### ISSUE THREAD

**Issue by olleharstedt** [amphp/amp#326]
Does `yield` always wait until all yielded commands are finished? Or is it possible to `yield` and continue running the function while the yielded command runs concurrently?

**Comment by enumag** [comment]
`yield` always waits. However you don't have to `yield` immediately. Instead of

```php
$result = yield doAsyncTask();
```

you can use

```php
$promise = doAsyncTask();
// do something else
$result = yield $promise;
```

That way you can `yield` and wait only when you have nothing else to do. You can also use [Promise Combinators](https://amphp.org/amp/promises/combinators) to make things easier in some cases.

**Comment by olleharstedt** [comment]
Thanks!

Related question: Would it be possible to have a 

```php
yield async($promise);
```

to return control before the promise is resolved?

**Comment by kelunik** [comment]
As far as I can tell `yield $promise` does what you want.

**Comment by olleharstedt** [comment]
> As far as I can tell `yield $promise` does what you want.

No, I want it to NOT wait. :)

**Comment by enumag** [comment]
`yield` only returns control when the yielded promise is resolved.

I'm not quite sure what exactly you want - does the behavior of your code after calling the async action changes based on whether it failed? If that's the case then do this:

```php
$promise = doAsyncTask();
// do something else
try {
    yield $promise;
} catch ($exception) {
    // ...
}
```

**Comment by olleharstedt** [comment]
I'm looking for something similar to goroutines:

> When a new Goroutine is started, the goroutine call returns immediately. Unlike functions, the control does not wait for the Goroutine to finish executing. The control returns immediately to the next line of code after the Goroutine call and any return values from the Goroutine are ignored.

https://golangbot.com/goroutines/

But, if it doesn't matter when a promise is resolved, I guess it's kind of the same thing to collect all in one array and just yield them all at the end? So

```php
yield async($promise1);
yield async($promise2);
```

would be the same as

```php
$doLater[] = $promise1;
$doLater[] = $promise2;
// More logic...
yield $doLater;
```

Maybe a function similar to `async()` can do this under the hood to make it look nice.

**Comment by enumag** [comment]
> When a new Goroutine is started, the goroutine call returns immediately. Unlike functions, the control does not wait for the Goroutine to finish executing. The control returns immediately to the next line of code after the Goroutine call and any return values from the Goroutine are ignored.

Okay... and what happens if a Goroutine fails? Is the exception also ignored?

**Comment by olleharstedt** [comment]
Go has no exceptions, but I guess you'd have to write via a channel to signal any result? Not sure, I'm not a Go programmer.

> Using a channel to return something is the only way you can guarantee to collect all return values from goroutines without overwriting them. There are multiple ways we can use the same return channels

https://www.atatus.com/blog/goroutines-error-handling/

In PHP land, I guess it would be impossible to catch any exception, so the promise itself should contain a try-catch. Or exceptions would bubble up at the end while waiting for all promises to resolve.

**Comment by enumag** [comment]
You could also use

```
$promise->onResolve(function (?\Throwable $exception) { if ($exception) { <error handling> } });
```

**Comment by olleharstedt** [comment]
OK, good tip!

**Comment by olleharstedt** [comment]
Closing this for now. Thanks for the feedback.

**Comment by olleharstedt** [comment]
Btw, here's an article arguing for the case of goroutines: http://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/

**Comment by trowski** [comment]
@olleharstedt I think you want to look into [`Amp\asyncCall()`](https://github.com/amphp/amp/blob/aab5b5f7cc9bef94ea2827d15bb27bb72ce32591/lib/functions.php#L119) and [`Amp\Promise\rethrow()`](https://github.com/amphp/amp/blob/aab5b5f7cc9bef94ea2827d15bb27bb72ce32591/lib/functions.php#L172). These functions might offer what you're looking for – they rethrow any promise failure to the event-loop error handler without awaiting the promise.

Keep in mind that `yield` within a coroutine awaits the promise result. It is not required for execution of the code to resolve the promise to begin. The operation is started when the promise object is created. You needn't ever yield a promise (or call `Promise::onResolve()` for the promise to be resolved. You can start any number of operations simultaneously and only await once the result is needed.

**Comment by olleharstedt** [comment]
> You can start any number of operations simultaneously and only await once the result is needed.

How?? With `yield`?

**Comment by trowski** [comment]
Yes, you can await the result of a number of promises using `Amp\Promise\all()`, or by yielding an array of promises (which is really just shorthand to yielding the promise returned by `all()`). The promise returned from `all()` fails if any promise fails and resolves only once all passed promises have resolved.

```php
$promise1 = asyncOp1();
$promise2 = asyncOp2();
$promise3 = asyncOp3();

[$result1, $result2, $result3] = yield [$promise1, $promise2, $promise3];
```

There are other functions in the `Amp\Promise` namespace for combining multiple promises to await them in different ways.

**Comment by olleharstedt** [comment]
:+1:
