### ISSUE TITLE
Mocking with Amphp

### ISSUE THREAD

**Issue by olleharstedt** [amphp/amp#327]
If you put all your side-effects (read/write to file, database, stdout etc) in command objects (following the command pattern), and inject only a side-effect command factory into your class, you basically don't have to mock anything, only the result of those commands, and your business logic will be pure. In Amphp it should be possible to do something similar, and I think it could reduce the problem with mocking a lot. How about writing something in the documentation about mocking promises for a class using Amphp? Or more general about testing.

As an example, compare https://github.com/amphp/mysql/blob/master/examples/2-simple-query.php with how (absolutely horrific) mocking can look with PHPUnit: https://www.leaseweb.com/labs/2015/03/unit-testing-phpunit-mocking-mysqli/

**Comment by olleharstedt** [comment]
Discussing thread: https://www.reddit.com/r/PHP/comments/i76zfy/achieving_functional_core_imperative_shell_using/

**Comment by kelunik** [comment]
I'm closing this, because it has been discussed elsewhere.
