### ISSUE TITLE
PHP CGI Emulation

### ISSUE THREAD

**Issue by mcarbonneaux** [amphp/amp#333]
while be interesting to implement PHP CGI variable emulation layer to permit to execute standard php library in AERYS or AMP HTTP-Server...  they while facilitate the reuse of existing php framework with power of amp... 

- https://www.php.net/manual/en/install.unix.commandline.php
- http://www.faqs.org/rfcs/rfc3875.html

the emulation layer must be abel to populate _SERVER with CGI variable : AUTH_TYPE, CONTENT_LENGTH, CONTENT_TYPE, GATEWAY_INTERFACE, PATH_INFO, PATH_TRANSLATED, QUERY_STRING, REMOTE_ADDR, REMOTE_HOST, REMOTE_IDENT, REMOTE_USER, REQUEST_METHOD, SCRIPT_NAME, SERVER_NAME, SERVER_PORT, SERVER_PROTOCOL, and SERVER_SOFTWARE

and also populate super globale (_POST/_GET/_COOKIE...) : https://www.php.net/reserved.variables.server 
and abel to execute php dynamicly from base directory (like static support in aerys) with php `eval` function for exemple...

**Comment by danog** [comment]
Ooo this would require an implementation of the FastCGI protocol in AMP, to later integrate it in http-server, seems like a fun project to do!

**Comment by mcarbonneaux** [comment]
no no fastcgi ! only local execution of php (wih `eval`) script with environement variable setted based on request.

**Comment by danog** [comment]
Using eval for synchronous code in async code makes no sense; if you really want to use legacy CGI (ew), we can simply wrap amphp/process or even amphp/parallel to start the php script; but it would be best to just use fastCGI, instead.

**Comment by mcarbonneaux** [comment]
using sync code in async code not make no sense, when you use pool of process to response to request is performante as using fastcgi or mod_php... and is standalone startup of php without nginx/apache/fpm or other thing... is pure php...
is pure php application server !
and is good to use in container...

in each request event the code are not all the time pur asynchronous... when reuse existing library (to avoid recoding) majority of them are developed sync...

**Comment by kelunik** [comment]
There's https://github.com/kelunik/gateway now to run requests using CGI and `amphp/http-server`.

**Comment by mcarbonneaux** [comment]
> There's https://github.com/kelunik/gateway now to run requests using CGI and `amphp/http-server`.

Ok but they use fork... And php-cgi binary ... This solution are very fat....

But is a good start to do the think....
