### ISSUE TITLE
suggestion: release event-loop as a seperate package

### ISSUE THREAD

**Issue by azjezz** [amphp/amp#345]
Hello 👋 

I recently started working on Asio component for [`azjezz/psl`](https://github.com/azjezz/psl), as well as IO component ( https://github.com/azjezz/psl/pull/127 ), using PHP ext-fiber, i found myself re-implementing an event loop, while it's possible to use amp, however, `amphp/amp` package provides way much more than i really need, as i'm trying to keep dependencies for PSL minimal-to-none ( currently, PSL doesn't depend on any other package ).

my suggestion is the following:

- move event loop class +`FoundationDriver`+`NativeDriver` ( and other internal classes ) to a new package ( e.g: `amphp/event-loop` )
- move each driver that depends on an extension to it's own package ( e.g: `amphp/uv-driver`, `amphp/event-driver`, `amphp/ev-driver` ... etc )

This allows me and others how want to build things on top of amp to depend on essentially only the necessary parts ( `amphp/event-loop` ), while the consumer can install a separate driver if they want to have a better performance.

However, I am aware that this is not an easy process, and can take time, therefor, I am willing to offer my help as much as possible 🙂

Thank you.

reference: https://twitter.com/azjezz/status/1370804427112779780 ( thread )

**Comment by trowski** [comment]
We discussed doing this yesterday shortly after that twitter thread. 😀

If the Fiber RFC is accepted, expect it to happen soon afterward.

There's not really a reason to have each driver in a separate package. Having a few bytes of unused PHP code around is probably fine vs. package bloat. However, you'll at least be getting just the event-loop related code and not everything else that is Amp.

**Comment by azjezz** [comment]
I have adopted amp event loop here for the time being until amp v3 is released.

https://github.com/azjezz/psl/tree/asio/src/Psl/Asio/Internal#amphp-event-loop

I'm not planning on releasing Asio component until PHP 8.1 is released so there's no rush :)

**Comment by kelunik** [comment]
This is now done at https://revolt.run/.
