### ISSUE TITLE
Connect amphp App to cPanel

### ISSUE THREAD

**Issue by Nedum84** [amphp/amp#347]
I have developed a restful API using amphp but i don't know how to configure it to work with cpanel. I need a guide on this.

**Comment by kelunik** [comment]
Hey @Nedum84, I'm not sure what you're trying to do exactly. Could you describe a bit more what you're trying to do and what doesn't work?

**Comment by Nedum84** [comment]
After developing my Restful api using amphp, and upload it to my cpanel
shared hosting account, I get the following error:

#2 {main}
  thrown in /home/utftufutv/public_html/app.topanswers.com/vendor/amphp/socket/src/TcpServer.php
on line 150
[17-Apr-2021 17:30:43 America/New_York] PHP Fatal error:  Uncaught
RuntimeException: Failed to listen on "tcp://127.0.0.1:8088": Address
already in use in
/home/utftufutv/public_html/app.topanswers.com/vendor/amphp/socket/src/TcpServer.php:165
Stack trace:

**Comment by kelunik** [comment]
If you're writing a server, you shouldn't run it with the Apache / FPM / CGI SAPI, but rather from the command line.
