### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by tristanpemble** [amphp/amp#349]
I spent my weekend learning and building with the Amp libraries and I want to pay it forward. This is a very well written suite of libraries, with a very clean API, and has been a delight to work with. OSS maintenance can be very challenging, and to maintain a consistent vision for a suite of libraries like this for as long as all of you have done is extraordinary!

Kudos :)

**Comment by kelunik** [comment]
Thank you for the kind words and your contribution!

I'm closing this, because we already have https://github.com/amphp/amp/issues/213 open.
