### ISSUE TITLE
Application structure

### ISSUE THREAD

**Issue by eleimt** [amphp/amp#351]
Hello
Tell me, how do you move the code out of the function? For example, I want to use http-client and websocket-client. Everything needs to be written inside `::run(function () { /* my long code */ })` or can I somehow put it in different files? Please tell me how to build applications from more than one file. I'm trying to figure out asynchronous PHP. Thanks.

**Comment by kelunik** [comment]
You can of course split your application into multiple files / classes. Loop::run with a callback is the equivalent of `Loop::defer` + running the loop, you can also have multiple defers or use `call` / `asyncCall` at various places. What's keeping you from using multiple files?

**Comment by eleimt** [comment]
Do you have any example how to require this things and where to write the functions? Where can I see an examples of implementation?

**Comment by kelunik** [comment]
Which kind of application do you want to build?

**Comment by eleimt** [comment]
I am trying to create an application that can communicate WS at a time with other services. Send WS to my GUI. Also communicate with DB, make requests for HTTP and, when zapeskoy, raise HTTP server

**Comment by eleimt** [comment]
Sorry for my english. Do you understand me?

**Comment by kelunik** [comment]
I do understand what you plan to implement, yes, but I don't have an example I can link right now. https://github.com/amphp/websocket-server/blob/f5e27858f2b9a37e909a3d96b50ab3420842e5b1/examples/stackexchange-questions/server.php Might help?

**Comment by eleimt** [comment]
Just using this example, I would like to understand how to break it down into honor. Maybe I don't have enough experience and understanding to understand, I don't know.

**Comment by kelunik** [comment]
Do your have your current source online somewhere? Maybe I can make specific suggestions then and we can work on concrete questions?

**Comment by eleimt** [comment]
Do you have Discord or Telegram? We can discuss it there. 
My contacts:
1. Discord: `eleimt#3606`
2. Telegram: `@eleimt`

**Comment by kelunik** [comment]
Yes, I do, you can join our group via https://t.me/amphpchat.

**Comment by xpader** [comment]
File a.php
```
<?php

require __DIR__.'/b.php';

\Amp\Loop::run(function() {
    yield request();
});

```

File b.php
```
<?php

use function Amp\call;

function request() {
    return call(function() {
        $request = new Request(..);
        return yield $existsClient->request($request);
    });
}
```
