### ISSUE TITLE
How to integration v3 with other asynchronous framework?

### ISSUE THREAD

**Issue by xpader** [amphp/amp#352]
For example I want integration v3 with Workerman or ReactPHP, But v3 has no Loop::run() method, I can't adapter v3 with these asynchronous framework's Event Loop.

For example:
```
$worker = new Worker('http://0.0.0.0:8005');
$worker->onMessage = function($connection, $data) {
    async(function() {
        delay(2000);
        return 'Hello World';
    })->onResolve(fn($e, $result) => $connection->send($result));
};

Worker::runAll();
```

This in workerman will never send message to connection.

For example:
```
$worker = new Worker('http://0.0.0.0:8005');
$worker->onMessage = function($connection, $data) {
    delay(2000);
    $connection->send('Hello World');
};

Worker::runAll();
```

This will block other onMessage until this delay finished.

I have tried: 
```
$worker->onMessage = asyncCallable(function($connection, $data) {
    delay(2000);
    $connection->send('Hello World');
});
```

Never run the callback.

I have no idea to use v3 with tradition callback asynchronous framework now, how??

**Comment by kelunik** [comment]
As with ReactPHP now, you'll need an event loop adapter, because there can always only be one event loop, otherwise they block each other. Where do you run Amp's event loop currently?

**Comment by enumag** [comment]
I just noticed that https://github.com/amphp/react-adapter doesn't have a v3 branch yet. Does that mean using react-based libraries in Amphp v3 is not supported yet? :thinking:

**Comment by xpader** [comment]
I have amp v2 event-loop adapter to [Workerman](https://github.com/walkor/Workerman) in my framework: [wind-framework/Amp.php](https://github.com/wind-framework/wind-framework/blob/main/src/base/Amp.php) .

But the question is these framework use callback on message coming, the v3 base on fiber block current stack except they're in different async(), I don't know how to run amp v3 in these framework callback and not block them, do I need to use defer() or asyncCallback() to make these framework's callback been asynchronous?

I have tried code like `$framework->onRequest = asyncCallback(function(){});`  doesn't work, `$framework->onRequest = function() { defer(function() {}); };` doesn't work.

Because framework's callback running in top scope of php, not in async() of amp, so one callback will block all other callback.

**Comment by xpader** [comment]
Look's like I have made the wrong test, I used browser to visit the server, and delay blocked each request, I think that because the browser `keep-alive` and framework have some problem, after I test it used curl in command line, the request can be concurrent.

I think the problem is been solved.

Thank you.
