### ISSUE TITLE
Reference to global constant is lost

### ISSUE THREAD

**Issue by ecairol** [amphp/amp#361]
I'm using AMP ParallelFunctions to invoke a function that will call an HTTP endpoint multiple times

The code looks something like this:

```
$result = wait( parallelMap( $myArray, function($item) use ($api) {
   return $api->call_api( $item );
} ) );
```

The function `$api->call_api` lives on a different file and grabs a Bearer token from a global constant. It throws the message `PHP Warning:  Use of undefined constant API_TOKEN` every time it's invoked by the async process (it runs ok as a synchronous process)

I suspect this happens because `parallelMap` makes use of a PHP worker that doesn't have access to the same scope where API_TOKEN was defined. Is that correct? If so, is there a solution?

Any ideas how to make `wait` and/or `parallelMap` to recognize a variable defined by `define('API_TOKEN', 'my-value')`?

**Comment by kelunik** [comment]
You're right, it makes use of workers which have their own scope. You can define a variable and `use ()` is in the closure.

If all you do is HTTP requests, it's better to rely on https://amphp.org/http-client/ instead, so you don't have to deal with workers at all.

**Comment by ecairol** [comment]
Thanks. I'll go with the local variable and `use()` approach.
