### ISSUE TITLE
No callback in v3 with revolt Future?

### ISSUE THREAD

**Issue by xpader** [amphp/amp#364]
In some cases, we need use callback like `$promise->onResolve()`, but in v3 with revolt, no Promise now, only Future, and can not found any way to do callback?

And there is no async, asyncCallback now?

use `fn() => coroutine($callback);` instead asyncCallback?

How do we do this like before, the FutureState is internal:
```
$defer = new Defered();

SomeOtherAsyncLib::afterJobIsDone(function() use ($defer) {
    //some code before
    $defer->resolve($result);
    //some code after
});

return $defer->promise();
```

**Comment by xpader** [comment]
What is the status of `then()`? Can it be merged into V3?

**Comment by kelunik** [comment]
We'll use `map` as method name and keep `then()` available for potential future use.
