### ISSUE TITLE
When can V3 be released？

### ISSUE THREAD

**Issue by tingfeng-key** [amphp/amp#370]
Does V3 support fibers? When will it be released? Is there a release schedule?

**Comment by xpader** [comment]
Ofcourse V3 base on Fiber.
I think there's no clear time point for v3 release yet.

**Comment by xpader** [comment]
PHP 8.1 is released.

**Comment by kelunik** [comment]
Our aim is to have an initial release of Revolt next week and then probably betas for most Amp libraries soon afterwards.

**Comment by tingfeng-key** [comment]
> Our aim is to have an initial release of Revolt next week and then probably betas for most Amp libraries soon afterwards.

OK, we look forward to your release and are preparing to make an application based on this function
