### ISSUE TITLE
Websocket server with while loop

### ISSUE THREAD

**Issue by wiryonolau** [amphp/amp#376]
Hi I have this scenario

- websocket server handling client subscription
- a while loop function that kept updating $variable periodically and publish to all connected client base on their subscription

There will be multiple subscription type and a while loop that updating the share variable.

Is it possible to do this ?
Will there be a thread unsafe scenario ?

**Comment by kelunik** [comment]
Hey @wiryonolau, yes, that's possible! You're probably looking for https://github.com/amphp/websocket-server. Amp uses cooperative multitasking on a single thread (apart from `amphp/parallel`), so you don't need to worry about thread safety issues. That said, there are obviously things that need some thought for concurrent access, e.g. writing from multiple places to `stdout` might not yield the result you expect, because lines might be intermixed.

**Comment by wiryonolau** [comment]
Can you a bit guide me where to start

I probably not going to output directly to stdout. File should be easier to handle.

Should I run a promise / parallel ( the while loop part  ) before starting HttpServer ?

There can only be one single Loop ?

**Comment by kelunik** [comment]
I suggest having a look at the getting started example, which is pretty much your use case: https://amphp.org/getting-started/tcp-chat/. It doesn't use websockets, but directly TCP sockets, but the same concepts will apply.

https://github.com/amphp/websocket-server/tree/f5e27858f2b9a37e909a3d96b50ab3420842e5b1/examples/stackexchange-questions will also be useful, as it covers a similar use case.

**Comment by wiryonolau** [comment]
Hi I test the code, some other question

1. If I use onStart how di I retrieve the client information ? 
2. Can  amphp/httpserver share session with normal php server ( nginx ) session ?

**Comment by kelunik** [comment]
onStart is called when the server starts. At that point, you don't have any clients, so also no client information.

Yes, it can share sessions, but there's no ready solution, it really depends on the session handling you're using.

**Comment by wiryonolau** [comment]
I get it now. it's two different things. Ok thanks. Nice library
