### ISSUE TITLE
The url inside the composer.json should be in their secure version?

### ISSUE THREAD

**Issue by S-Tian86** [amphp/amp#377]
Hi,

I think the url should be written with https;// instead of http://.
https://github.com/amphp/amp/blob/5c29da05afd44248a6d15abb29ecf8eabb0af814/composer.json#L3

What do you think?

Regards

**Comment by kelunik** [comment]
Sure, do you want to send a PR?

**Comment by S-Tian86** [comment]
Sure, no problem.
