### ISSUE TITLE
A concise way of resolving results that may turn out to be Promise, Generator or something else

### ISSUE THREAD

**Issue by tncrazvan** [amphp/amp#392]
First of all thanks for the great work.

---

I have a feeling this might be a stupid question, but here I go.

How would you go on about resolving the result of a function/method that returns `:Promise|ReactPromise|Generator|SomeOtherType`  without doing this
```php
$result = myFunction();  //may return a Promise, Generator or something else
if($result instanceof \Generator)
	yield from $result;
if($result instanceof \Amp\Promise)
	yield $result;
if($result instanceof \React\Promise\PromiseInterface)
	yield \Amp\Promise\adapt($result);
```

`\Amp\call` is so close to solving this yet so far and `\Amp\Coroutine` takes only `Generator`s.
Am I missing something or is that the only way?

Or maybe this a practice that's discouraged?

**Comment by tncrazvan** [comment]
But it takes a `callable`, no?

https://github.com/amphp/amp/blob/9d5100cebffa729aaffecd3ad25dc5aeea4f13bb/lib/functions.php#L87

It throws the following using a generator:
```
Uncaught TypeError: Amp\call(): Argument #1 ($callback) must be of type callable, Generator given
```

**Comment by kelunik** [comment]
Yes, `(...)` is PHP 8.1's first class callable syntax, not an omission. If you already have a value, you can also use `Amp\call(fn () => $value)`.

**Comment by tncrazvan** [comment]
> Yes, (...) is PHP 8.1's first class callable syntax

I see, that does it.

Thanks a lot!
