### ISSUE TITLE
Support systemd.socket

### ISSUE THREAD

**Issue by ParkFramework** [amphp/amp#40]
Hello.

Need support systemd.socket. This will make, activation and reload demon save all open connections.
https://www.freedesktop.org/software/systemd/man/systemd.socket.html#

Is planned implement?
Thank.

**Comment by bwoebi** [comment]
I'm not really sure how that's amp's business. Amp is only providing readability and writability watchers, not creating or managing sockets.

**Comment by kelunik** [comment]
Might be something for `amphp/socket` or an own `systemd` package.

**Comment by ParkFramework** [comment]
Yes, it should be `amphp/socket`, but how to do user land PHP, I do not know.

**Comment by ParkFramework** [comment]
`amphp.socket`
```
[Socket]
Backlog       = 1024
ListenStream  = /run/www/amphp.sock

[Install]
WantedBy = sockets.target
```

`amphp.service`
```
[Service]
ExecStart = /var/www/amphp/server.php

[Install]
WantedBy = multi-user.target
```
Get env params in `server.php`:
`$_SERVER['LISTEN_FDS']` // 1 - file descriptor
`$_SERVER['LISTEN_PID'];` // current pid

But how to work with them and open the connection, I do not know :)

**Comment by kelunik** [comment]
Closing, because it's nothing for `amphp/amp`. I think something like that should be it's own package.
