### ISSUE TITLE
UnhandledFutureError is hard to debug

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#404]
Currently, we don't offer good / any debugging tools to debug and fix unhandled future errors. This makes them annoying and very hard to find and fix.

**Comment by kelunik** [comment]
See https://github.com/ScriptFUSION/Async-Throttle/commit/83c311a747d63c39a788f7e6f3da7ce66eeee8d7.

**Comment by trowski** [comment]
Closed via #405.
