### ISSUE TITLE
Migration guide for combinator functions

### ISSUE THREAD

**Issue by Bilge** [amphp/amp#406]
Owing to the fact that v2's `Promise\any` would accept an empty array, its v3 analogue `awaitAny` should do the same, but it does not; it requires at least one element in the iterable collection otherwise it throws:

> In functions.php line 91:
  [Amp\CompositeLengthException]                                                      
  Argument #2 ($futures) contains too few futures to satisfy the required count of 1  

Due to this, we need to remember to guard against the empty array case when migrating, which is error prone.

**Comment by kelunik** [comment]
The equivalent to `Amp\Promise\any` is `Amp\Future\awaitAll`, which doesn't require at least one future. The name changes can be quite confusing there.

**Comment by Bilge** [comment]
Certainly a migration guide to this effect would be handy. I suppose otherwise this ticket is moot.

**Comment by kelunik** [comment]
It exists, but it's wrong 👀  https://github.com/amphp/amp/releases/tag/v3.0.0-beta.9

Actually, not just the guide is wrong, but the previous compat layer was also wrong.

**Comment by Bilge** [comment]
lul

**Comment by kelunik** [comment]
Fixed in the `CHANGELOG.md`.
