### ISSUE TITLE
Shouldn't Future::finally() pass the future data to the provided callback?

### ISSUE THREAD

**Issue by dmiedev** [amphp/amp#424]
I'm a little perplexed by the fact that you can't obtain the future data from the arguments (as nothing is passed).

**Comment by xpader** [comment]
You mean future resolved data pass to finally callback?

**Comment by dmiedev** [comment]
Yes...

**Comment by kelunik** [comment]
Why do you except / need it there?

**Comment by dmiedev** [comment]
Well, I didn't find a way to await for the value without blocking the thread. If I understand correctly, await() is not non-blocking. I guess there is also map(), maybe I could use that

**Comment by xpader** [comment]
You should do something in map() callback that depends on resolved value.
And await block your code executing of current stack, but no block your process.
You can have lots of coroutine running concurrent.

**Comment by kelunik** [comment]
await just blocks the current fiber, but if you want to avoid that, use map() or catch(), depending on whether you want to work with the successful completion value or error. finally() is always called, like a finally block, and the result might be an error or not, so we don't provide any info there. If you need different behavior on success / error, use map() / catch().

**Comment by dmiedev** [comment]
Okay, got it :) Thanks!
