### ISSUE TITLE
Future combinators

### ISSUE THREAD

**Issue by vudaltsov** [amphp/amp#426]
I am new to async PHP, so I might be missing smth. Why amphp v3 does not have any Future combinators?

Here's how I return single Future for two operations now (btw, is it correct?):

```php
async(static fn (): array => await([
    async(static function (): void { delay(2); }), // some IO
    async(static function (): void { delay(3); }), // another IO
]));
```

Wouldn't it be nicer to do smth like?

```php
all([
    async(static function (): void { delay(2); }), // some IO
    async(static function (): void { delay(3); }), // another IO
]);
```

Thanks for the project. I am having a lot of fun with it!

**Comment by Bilge** [comment]
See https://github.com/amphp/amp/blob/3.x/src/Future/functions.php. You probably want `awaitAll()`.

**Comment by vudaltsov** [comment]
@Bilge , no, I want a function that immediately returns a single `Future`, not awaited result.

**Comment by Bilge** [comment]
I have no idea what you're talking about.

**Comment by vudaltsov** [comment]
Well, I am talking about a function like [React\Promise\all](https://github.com/reactphp/promise#all). It returns **Promise**, not awaited result array like `await` in amphp.

> Returns a promise that will resolve only once all the items in $promisesOrValues have resolved. The resolution value of the returned promise will be an array containing the resolution values of each of the items in $promisesOrValues.

**Comment by vudaltsov** [comment]
Let me put it this way:

`Amp\Future\await()` is `callable(iterable<TKey, Future<TValue>>): array<TKey, TValue>`

But I want `callable(iterable<TKey, Future<TValue>>): Future<array<TKey, TValue>>`

**Comment by vudaltsov** [comment]
@Bilge , does it make sense now? I can give an example of problem I am solving.

Here are similar methods/functions in other langiuages: [JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all), [C#](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenall?view=net-8.0#system-threading-tasks-task-whenall(system-collections-generic-ienumerable((system-threading-tasks-task)))). Note that return type is different from `Amp\Future\await` or `Amp\Future\awaitAll`.

**Comment by kelunik** [comment]
You can wrap it in async() if you really need that, but we use futures rarely with fibers, only when necessary.

**Comment by vudaltsov** [comment]
Thank you, @kelunik, that makes sense! After three days of experimenting with amphp 3 I now understand, why await combinators are much more useful.
