### ISSUE TITLE
Cannot tick() recursively; event reactor already active

### ISSUE THREAD

**Issue by chrisleavoy** [amphp/amp#47]
I feel like this is going to be a common pitfall so I'm creating an issue for tracking. I'm finding that not being able to synchronously wait within an asynchronous context is overly limiting. Contrived example:

```php
\Amp\run(function() {
    var_dump(\Amp\wait(\Amp\Dns\resolve('google.ca')));
});
```

This code throws 
```
'LogicException' with message 'Cannot tick() recursively; event reactor already active'
```
More commonly when adapting old synchronous code is to have asynchronous promises higher in the call stack and various yields lower in the call stack. Its quite annoying to pass promises and chain the entire call stack.

I've created a gist with a more complete example of what I'm trying to accomplish: https://gist.github.com/chrisleavoy/9c2386e3b408399c4ba2e5a4db055888

Can someone recommend a better workaround?

The leading contender right now is to use Icicle's loop reactor, but then adapt promises so that i can use Amp\Dns instead of Icicle's DNS implementation. Kudos on Amp\Dns, which is the best library I've found when evaluating all of the php async packages for DNS.

Working example that uses Icicle but embeds Amp\Dns:
https://gist.github.com/chrisleavoy/18b4032402d7b2d7f688655fe28eab60

I would appreciate some insight into reasons why Amp throws this logic exception and whether there is a work around that doesn't involve converting the entire call stack into async. (php5.5 support required)

**Comment by staabm** [comment]
In case you like to wait "synchronously" for a promise, just `yield` it.

```php
\Amp\run(function() {
    $promise = \Amp\Dns\resolve('google.ca');
    $result = yield $promise;
    var_dump($result);
});
```

**Comment by bwoebi** [comment]
@staabm He knows that…

By the way, your icicle example works as expected (or not?) as it does not wait on the same loop, but once on the icicle loop, once on the amp loop.

The main issue with wait() inside already async context is that it leads to heavy recursion which may or may not fail depending on whether a certain generator is already in your stack trace (cannot resume a current running Generator). It's a large pitfall which may only happen in more complex applications.
Also, the VM only continues after a wait() if all calls afterwards to wait() are resolved (due to the way stacktraces work. That's what we have Generators for!).

Thus we forbid this explicitly. You have to yield Promises or yield from Generators. That's an inherent requirement which we cannot lift without making Amp very unstable.

**Comment by chrisleavoy** [comment]
Surprisingly, my icicle example works great. Amp\Dns\Resolve yields just fine inside the Icicle loop.

I can't leverage yield, becaus yield isn't allowed in the same function with a return.  And I can't pass promises up the entire stack where the Amp context is created because I have a middle layer I don't want to change.  So unless I'm missing something, its impossible to use a generator inside an \Amp\wait() context, which is the heart of my issue.

IE this is not allowed:
```php
\Amp\run(function() {
    function resolve() {
        $promise = \Amp\Dns\resolve('google.ca');
        $result = (yield $promise);
        return ($result);
    }
    var_dump(resolve());
});
```
```PHP Fatal error:  Generators cannot return values using "return"```

**Comment by bwoebi** [comment]
Looks like you are using PHP 5.

In this case you may `yield new \Amp\CoroutineResult($result);` instead of a return.

**Comment by kelunik** [comment]
@chrisleavoy It's not possible. You can't do it with the middle being unaware of promises.

**Comment by bwoebi** [comment]
oh, you want to explicitly run synchronously.

In this case you have to replace the reactor around that:

```php
$old = \Amp\reactor(\Amp\driver())
$result = \Amp\wait(resolve());
\Amp\reactor($old);
```

**Comment by chrisleavoy** [comment]
Thats not quite what I need. In my example gist, (updated: https://gist.github.com/chrisleavoy/9c2386e3b408399c4ba2e5a4db055888)  I'll have 4 or more parallel "plugins" running asynchronously. Each plugin has a synchronous function and waits for the underlying DNS query, which should yield in the outer Amp reactor letting other plugins run when ready. If I create multiple Amp reactors, the yield doesn't work.  In my Icicle example (https://gist.github.com/chrisleavoy/18b4032402d7b2d7f688655fe28eab60) parallel Amp\waits inside one outer Icicle reactor, seems to work. Ideally I'd like to get this working without Icicle though.

**Comment by bwoebi** [comment]
https://gist.github.com/bwoebi/7cba5729647b7ee76fcc337a06e0a5ed

You must keep your functions async between each other. You must call `Amp\wait()` _only_ outside the async tree.
There is no way around that; this is inherent to Amp and Icicle.

**Comment by chrisleavoy** [comment]
Darn.

Thanks so much for the schooling.  Much appreciated. I was really trying not to chain the entire call stack but it sounds like its not possible.  On closer debugging, my Iclcle/Amp mix, wasn't actually async. I had only made it so overly complicated that I wasn't tracing it properly. 😆

**Comment by bwoebi** [comment]
No problem, people who have coded always sync before all have similar problems...

Happy to help out and make you understand the concepts properly!
