### ISSUE TITLE
Comparison of extensions

### ISSUE THREAD

**Issue by flip111** [amphp/amp#52]
Does anyone know how the backend extensions compare in terms of CPU usage, memory usage and wall time?

**Comment by kelunik** [comment]
I don't have any such numbers. I have personally only used `uv` so far. I think `libevent` doesn't have a PHP 7 version. I didn't try `ev` yet.

**Comment by kelunik** [comment]
It's something we should have in the documentation, but for https://github.com/amphp/loop then.

**Comment by kelunik** [comment]
We're using Revolt in Amp v3, so this is something that needs to be documented on https://revolt.run/extensions instead.
