### ISSUE TITLE
PHP 7.1 has async signal handling?

### ISSUE THREAD

**Issue by withinboredom** [amphp/amp#64]
https://wiki.php.net/rfc/async_signals

I don't really know what this means, but hey, you guys probably know what they're talking about.

**Comment by bwoebi** [comment]
This means exactly nothing for us.

In an event-loop, we want synchronous signal handling (i.e. signals being dispatched consecutively and not within other loop callbacks).

As the default is synchronous handling, this has absolutely no impact on our code.
