### ISSUE TITLE
Wrong defer watcher try / catch

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#74]
https://github.com/amphp/amp/blob/8f903b62db5d3696bdff2c9beab0a9081f372267/lib/Loop/Driver.php#L112 should have the `try` / `catch` around the `$callback` invocation, not around the `foreach`.

**Comment by trowski** [comment]
That `try` / `catch` block catches exceptions thrown from *any* watcher invocation, not just defers, as it is also around the call to `dispatch`. Any watcher callback throwing an exception effectively immediately ends the tick. In this way defers are handled the same as any other watcher.

**Comment by kelunik** [comment]
It makes handling easier, but it won't execute any I/O watchers if there's always one defer throwing.

**Comment by trowski** [comment]
I can't imagine that happening in an actual app.

**Comment by kelunik** [comment]
Same here, that'd be an extreme edge case, but it might happen, as we use `Loop::defer` to rethrow errors from promises.

**Comment by trowski** [comment]
@bwoebi After thinking about this, I realized an app might have a IO, timer, or signal that continually throws that might block another watcher from ever executing that would stop the cycle. I'll update everywhere watcher callbacks are invoked to be wrapped by their own `try` / `catch` blocks and continue the tick after calling the loop error handler.
