### ISSUE TITLE
Invalid yields

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#82]
Currently, `InvalidYieldError`s are thrown back into the generator. I'm not sure whether that's a good idea. Maybe they should directly be forwarded to the error handler and the coroutine aborted?

**Comment by joshdifabio** [comment]
But the promise of the "aborted" coroutine would still resolve with an error, right?

**Comment by kelunik** [comment]
I guess it does already exactly that with `dispose()`.

https://github.com/amphp/amp/blob/76c412a80236ee2d9a8e229f2e8254f81117b95f/lib/Coroutine.php#L150-L168

**Comment by trowski** [comment]
@kelunik Largely I run the generator to completion to avoid weird behavior from `finally` blocks throwing when the generator object is destructed. I'm not sure if I can rely on the generator object being immediately destructed when the property holding the generator is nulled.

**Comment by kelunik** [comment]
As instances of `Error` shouldn't be caught, it shouldn't matter anyway.

**Comment by bwoebi** [comment]
@kelunik The Generator may want to log these errors, recover and continue though...
Thus I'm against changing this.

**Comment by kelunik** [comment]
@bwoebi It can't recover that already, have a look at `dispose`.

**Comment by trowski** [comment]
@bwoebi It can log and clean up, but attempts to yield a promise again no longer work (the exception is just thrown back in). Should we allow the coroutine to continue or leave it as-is? As it's a coding error, I'm not sure it really matters…
