### ISSUE TITLE
Stopping nested loops

### ISSUE THREAD

**Issue by trowski** [amphp/amp#84]
Nested loops can result in cases where multiple calls to stop are timed in such a way that the lower-level loop does not stop.

This code continues the base loop indefinitely, even though it seems it should be stopped.

```php
Loop::run(function () {
    Loop::repeat(1000, function () {
        print microtime(true) . PHP_EOL;
    });

    Loop::defer(function () {
        Loop::stop();
    });

    Loop::run(function () {
        Loop::stop();
    });
});
```

While this is an edge-case, I can see this potentially happening if multiple calls to `wait()` are made and the promises are resolved in the same tick.

This happens because we ignore multiple calls to stop. Perhaps multiple calls should not be ignored, but rather stop the prior loop if running as a nested loop.

**Comment by kelunik** [comment]
I think we shouldn't care about this case and instead forbid `Amp\wait` in case the loop is running.

But that might not work for shutdown functions, right?

**Comment by trowski** [comment]
We'd need a way to tell if the loop is running to forbid it in `Amp\wait`. Not a problem to add, but currently is missing from `Driver`.

This could be an issue in shutdown functions as you suggested. If each function starts their own event loop, subsequently calling `stop`, the likelihood of calls to `stop` occurring in the same tick might be may be high…

**Comment by kelunik** [comment]
@trowski We already have a `"running"` boolean in `getInfo()`.

**Comment by kelunik** [comment]
Would be cool if we could access https://github.com/php/php-src/blob/c6982995504b6e21e8a5ade29cfb16a55196dc43/main/main.c#L1808 and disable the recursive run protection in that case.

**Comment by kelunik** [comment]
@trowski I think a single `Loop::stop()` should just stop all recursive runs and further `Loop::stop()` calls should still be ignored.

**Comment by trowski** [comment]
Addressed with https://github.com/amphp/amp/commit/173549ebbac46c427627a11e07287b938a063d41.
