### ISSUE TITLE
Use monotonic time source

### ISSUE THREAD

**Issue by kelunik** [amphp/amp#94]
We should use a monotonic time source where available. We might have one available in PHP 7.2 via https://github.com/php/php-src/pull/2368. UV already uses it's `uv_hrtime` which is monotonic.

For `Ev` we should maybe have a look at our current implementation. https://github.com/reactphp/event-loop/pull/83#issuecomment-286676276 mentions real time vs. wall time.

**Comment by rhclayto** [comment]
See http://docs.php.net/manual/en/class.evperiodic.php

**Comment by kelunik** [comment]
These docs are highly confusing. Wall clock time is usually the time as measured by a stopwatch, but refers to absolute time here. `EvTimer` is the right thing to use according to the example.

**Comment by rhclayto** [comment]
I agree, their terminology is backwards. In the pull request you referenced,  I used EvTimer too. I just thought I would mention that there are docs out there, although, yes, they may confuse matters, but people may be referring to them & end up talking at cross-purposes. Cheers.

**Comment by kelunik** [comment]
This has been implemented via https://github.com/amphp/amp/commit/5622edba3752578e12166de664e8bceab45f4aa3.
